credebl/platform

apps/api-gateway/src/user/dto/add-user.dto.ts, apps/api-gateway/src/user/user.controller.ts, apps/api-gateway/src/user/user.service.ts, apps/user/interfaces/user.interface.ts, apps/user/repositories/user-device.repository.ts, apps/user/repositories/user.repository.ts, apps/user/src/user.controller.ts, apps/user/src/user.module.ts, apps/user/src/user.service.ts, libs/common/src/response-messages/index.ts, libs/prisma-service/prisma/migrations/20230831142029_user_device_password/migration.sql, libs/prisma-service/prisma/migrations/20230905103154_password_user/migration.sql, libs/prisma-service/prisma/schema.prisma
- Stored password while adding the passkey
- Changed login, and signup  approach for passkey
- Login Approach with Passkey:
Users can now log in using their passkeys in addition to their regular usernames or email addresses.
The application has likely added a feature to authenticate users based on their passkey, which might involve decrypting or verifying the passkey to grant access.
- Signup Approach with Passkey:
During the signup process, users may have the option to create a passkey in addition to a traditional password.
The application may enforce certain security requirements for passkeys, such as length and complexity.
=> feat/fix: Updated passkey Implementation for supabase

apps/api-gateway/src/fido/fido.controller.ts, apps/user/src/user.service.ts
=> fix: changed login error message

apps/api-gateway/src/organization/dtos/update-organization-dto.ts, apps/api-gateway/src/organization/organization.controller.ts, apps/api-gateway/src/organization/organization.service.ts, apps/api-gateway/src/user/dto/update-user-profile.dto.ts, apps/api-gateway/src/user/user.controller.ts, apps/api-gateway/src/user/user.service.ts, apps/organization/dtos/create-organization.dto.ts, apps/organization/interfaces/organization.interface.ts, apps/organization/repositories/organization.repository.ts, apps/organization/src/organization.controller.ts, apps/organization/src/organization.service.ts, apps/user/interfaces/user.interface.ts, apps/user/repositories/user.repository.ts, apps/user/src/user.controller.ts, apps/user/src/user.service.ts
- Refactored the PUT API `/users` for the `isPublic` flag.
- Refactored the PUT API `/organizations` for the `isPublic` flag.
- Created an `orgSlug` for organizations.
- Implemented the `username` of the user for public profiles.
=> feat: implemented username & orgslug feature for public profiles

apps/user/src/user.service.ts, libs/prisma-service/prisma/data/credebl-master-table.json, libs/prisma-service/prisma/migrations/20231003080927_ecosystem_flag/migration.sql, libs/prisma-service/prisma/migrations/20231003114625_ecosystem_logo/migration.sql, libs/prisma-service/prisma/schema.prisma, libs/prisma-service/prisma/seed.ts
- Included `enableEcosystem` flag in the user profile details.
=> refactor: enable disable ecosystem: 107

apps/api-gateway/src/ecosystem/dtos/send-invitation.dto.ts, apps/api-gateway/src/ecosystem/ecosystem.controller.ts, apps/api-gateway/src/ecosystem/ecosystem.service.ts, apps/ecosystem/dtos/send-invitation.dto.ts, apps/ecosystem/enums/ecosystem.enum.ts, apps/ecosystem/src/ecosystem.controller.ts, apps/ecosystem/src/ecosystem.repository.ts, apps/ecosystem/src/ecosystem.service.ts, apps/ecosystem/templates/EcosystemInviteTemplate.ts, libs/common/src/response-messages/index.ts
- Created `enum` for `EcosystemInvitationStatus`.
- Worked on the send invitation to join ecosystem feature.
=> feat: ecosystem send invitation

Dockerfiles/Dockerfile.ecosystem
- Created dockerfile for ecosystem microservice
=> Added dockerfile for ecosystem microservice

apps/api-gateway/src/ecosystem/ecosystem.service.ts, apps/ecosystem/interfaces/ecosystem.interfaces.ts, apps/ecosystem/src/ecosystem.repository.ts, apps/ecosystem/src/ecosystem.service.ts, libs/common/src/response-messages/index.ts
- Added organization validation for create and invite for ecosystem.
=> refactor: organization validation for create and invite for ecosystem

apps/api-gateway/src/ecosystem/ecosystem.controller.ts, apps/ecosystem/src/ecosystem.service.ts, apps/ecosystem/templates/EcosystemInviteTemplate.ts, libs/common/src/send-grid-helper-file.ts
- Refactor Ecosystem Send invitations link for user
- Add Ecosystem roles guard
=> refactor: send ecosystem invitation link

apps/ecosystem/src/ecosystem.repository.ts
- Fixed empty resourceId issue for the ecosystem's schema list
=> fix: handled empty resourceId for ecosystem's schema list

apps/api-gateway/src/user/user.controller.ts, apps/api-gateway/src/user/user.service.ts, apps/ecosystem/src/ecosystem.repository.ts, apps/ecosystem/src/ecosystem.service.ts, apps/user/repositories/user.repository.ts, apps/user/src/user.controller.ts, apps/user/src/user.service.ts, libs/common/src/response-messages/index.ts, libs/org-roles/repositories/index.ts
- Included GET API for platform settings
- refactored the get organization roles
- To display the platform and ecosystem settings to platform admin.
=> refactor: GET API of platform config settings

apps/organization/repositories/organization.repository.ts
- Sort organisations in descending order based on their name
- Get sorted organisation list by name
By adding OrderBy object inside query object
=> Sort organizations in descending order based on their name

libs/prisma-service/prisma/schema.prisma
-  Included pool database URL in schema prisma
- To use the connection pooling for postgres DB.
=> fix: connection pool of prisma postgres

libs/prisma-service/prisma/migrations/20231116112146_status_file_data/migration.sql, libs/prisma-service/prisma/migrations/20231116114452_credentials_file_data/migration.sql, libs/prisma-service/prisma/schema.prisma
-  Included `status`,  `schemaId` and `credDefId` in the `file_data` model
- To bulk issue the credentials for user.
=> refactor: bulk issuance file data model 

apps/api-gateway/src/app.module.ts, apps/api-gateway/src/authz/socket.gateway.ts, apps/api-gateway/src/enum.ts, apps/api-gateway/src/issuance/dtos/issuance.dto.ts, apps/api-gateway/src/issuance/interfaces/index.ts, apps/api-gateway/src/issuance/issuance.controller.ts, apps/api-gateway/src/issuance/issuance.service.ts, apps/issuance/interfaces/issuance.interfaces.ts, apps/issuance/src/issuance.controller.ts, apps/issuance/src/issuance.module.ts, apps/issuance/src/issuance.processor.ts, apps/issuance/src/issuance.repository.ts, apps/issuance/src/issuance.service.ts, libs/common/src/response-messages/index.ts
- Implemented retry for bulk-issuance
- Changed logic for issuance (Implemented loop for bulk-issuance)
=> feat: bulk issuance retry

apps/api-gateway/src/authz/socket.gateway.ts, apps/issuance/interfaces/issuance.interfaces.ts, apps/issuance/src/issuance.repository.ts, apps/issuance/src/issuance.service.ts, libs/common/src/response-messages/index.ts
- socket issue and error handling
- Implemented delete issued credential data
=> fix: socket issue and error handling

apps/agent-service/src/agent-service.service.ts, apps/issuance/src/issuance.service.ts, apps/ledger/src/credential-definition/repositories/credential-definition.repository.ts, apps/verification/src/interfaces/verification.interface.ts, apps/verification/src/verification.service.ts
1. Added the label on the out-of-band issuance and verification payload
=> fix: added label for the out-of-band issuance and verification

apps/issuance/templates/out-of-band-issuance.template.ts
=> refact:changed email template and added social media logo

apps/api-gateway/src/connection/connection.controller.ts, apps/api-gateway/src/connection/connection.service.ts, apps/api-gateway/src/issuance/issuance.service.ts, apps/api-gateway/src/platform/platform.controller.ts, apps/api-gateway/src/platform/platform.service.ts, apps/connection/src/connection.repository.ts, apps/issuance/interfaces/issuance.interfaces.ts, apps/issuance/src/issuance.controller.ts, apps/issuance/src/issuance.repository.ts, apps/issuance/src/issuance.service.ts, apps/issuance/templates/out-of-band-issuance.template.ts, apps/ledger/src/ledger.controller.ts, apps/ledger/src/ledger.service.ts, apps/ledger/src/repositories/ledger.repository.ts, apps/user/templates/arbiter-template.ts, apps/user/templates/participant-template.ts, apps/user/templates/winner-template.ts, apps/user/templates/world-record-template.ts, libs/prisma-service/prisma/migrations/20231124163136_ledger_network_url/migration.sql, libs/prisma-service/prisma/schema.prisma
-  Refactored connections, credentials and presentations table
=> refactor: Dev to main

apps/issuance/templates/out-of-band-issuance.template.ts
-  Refactor oob mail template logo url
=> refactor: oob mail template logo url

apps/api-gateway/src/ecosystem/dtos/accept-reject-invitations.dto.ts, apps/api-gateway/src/ecosystem/dtos/create-ecosystem-dto.ts, apps/api-gateway/src/ecosystem/ecosystem.controller.ts, apps/ecosystem/dtos/accept-reject-ecosysteminvitation.dto.ts, apps/ecosystem/dtos/update-ecosystemOrgs.dto.ts, apps/ecosystem/interfaces/ecosystem.interfaces.ts, apps/ecosystem/src/ecosystem.repository.ts, apps/ecosystem/src/ecosystem.service.ts, libs/common/src/response-messages/index.ts, libs/prisma-service/prisma/migrations/20231127132350_map_ecosystem_orgs/migration.sql, libs/prisma-service/prisma/schema.prisma, libs/prisma-service/prisma/seed.ts
- Mapped `ecosystem` and `organization` model
- Refactored create ecosystem dto and query.
- Refactored accept/ reject ecosystem invitation dto and query.
- Refactored ecosystem members list GET API 
- To get ecosystem `organization` details
=> refactor: ecosystem organization model mapping

apps/api-gateway/common/exception-handler.ts, apps/api-gateway/src/issuance/dtos/issuance.dto.ts, apps/api-gateway/src/issuance/issuance.controller.ts, apps/issuance/src/issuance.service.ts, libs/common/src/response-messages/index.ts
- Refactor POST API for Out-of-band issuance for multiple records.
- To create multiple credential offer at same time.
- To handle and process multiple records at same time.
=> feat: oob issuance for multiple records

apps/ecosystem/interfaces/ecosystem.interfaces.ts, apps/ecosystem/src/ecosystem.repository.ts, apps/organization/repositories/organization.repository.ts, apps/organization/src/organization.service.ts
API Response Refactoring for the following APIs:
- Get Ecosystem Details 
- Get Organization By Id
- Get all public profile of organizations
- Get public profile of specific organization
=> refactor:Api response

apps/api-gateway/src/interfaces/ISchemaSearch.interface.ts, apps/api-gateway/src/platform/platform.controller.ts, apps/api-gateway/src/schema/dtos/get-all-schema.dto.ts, apps/ledger/src/schema/interfaces/schema-payload.interface.ts, apps/ledger/src/schema/repositories/schema.repository.ts
- Implement a function to retrieve a list of all schemas by network.
- To retrieve a list of all schemas by network is essential for seamless credential definition creation. 
- By having a comprehensive list of schemas available within the selected network, potential issues related to mismatched or unavailable schemas can be preemptively addressed. 
- This ensures that cred-def creation is accurate, preventing problems that may arise from incompatible schema information during the credential definition process.
=> refactor: retrieve list of all schemas by network

apps/api-gateway/src/user/dto/accept-reject-invitation.dto.ts, apps/user/interfaces/user.interface.ts, apps/user/repositories/user.repository.ts, apps/user/src/user.controller.ts, apps/user/src/user.service.ts, libs/user-activity/interface/index.ts, libs/user-activity/repositories/index.ts, libs/user-activity/src/user-activity.service.ts
1) API response refactoring for the following APIs in Users module:
- Fetch login user details.
- Fetch organization invitations.
2) Checked API response, dto validations and promise return type, for all API's in user module.
=> refactor:  API response

apps/agent-service/src/agent-service.service.ts, apps/api-gateway/common/exception-handler.ts, apps/api-gateway/common/interface.ts, apps/api-gateway/src/authz/guards/org-roles.guard.ts, apps/api-gateway/src/dtos/create-schema.dto.ts, apps/api-gateway/src/schema/schema.controller.ts, apps/api-gateway/src/schema/schema.service.ts, apps/ledger/src/schema/interfaces/schema.interface.ts, apps/ledger/src/schema/repositories/schema.repository.ts, apps/ledger/src/schema/schema.controller.ts, apps/ledger/src/schema/schema.service.ts, libs/common/src/cast.helper.ts, libs/common/src/response-messages/index.ts
- Refactored the POST API for `/orgs/{orgId}/schemas`.
- Handled all the validations and negative scenarios.
- Refactored global exception handler.
=> refactor: Create Schema

apps/api-gateway/src/authz/authz.controller.ts, apps/api-gateway/src/authz/authz.service.ts, apps/api-gateway/src/user/dto/email-verify.dto.ts, apps/api-gateway/src/user/user.controller.ts, apps/api-gateway/src/user/user.service.ts, apps/user/interfaces/user.interface.ts, apps/user/repositories/user.repository.ts, apps/user/src/user.controller.ts, apps/user/src/user.service.ts, libs/common/src/response-messages/index.ts
- Refactored following APIs:
1. GET API `/auth/verify` to Verify user’s email.
2. POST  API`/auth/verification-mail` to Send verification mail.
3. GET API `/users/{email}` to Check user exist.
1. Implemented a well-defined interface by replacing previous existing `Promise<object>`.
4. Ensured consistency of API status codes.
5. Modified the NATS function.
6. Tested with both positive and negative scenarios.
1. Replaced the return type with a well-defined interface to enhance code clarity.
2. Checked and standardized API status codes to ensure a uniform response.
3. Modified the NATS function to accommodate the adjustments made in the API.
1. The implementation of a well-defined interface enhances code readability and makes the structure of the API response more explicit.
2. Ensuring …
=> Refactor user and auth module APIs

apps/agent-service/src/agent-service.controller.ts, apps/agent-service/src/agent-service.service.ts, apps/agent-service/src/interface/agent-service.interface.ts, apps/agent-service/src/repositories/agent-service.repository.ts, apps/api-gateway/src/agent-service/agent-service.controller.ts, apps/api-gateway/src/agent-service/agent-service.service.ts, apps/api-gateway/src/agent-service/dto/create-tenant.dto.ts, apps/api-gateway/src/agent-service/interface/agent-service.interface.ts, libs/common/src/response-messages/index.ts, libs/prisma-service/prisma/migrations/20231227105815_org_id_unique_org_agent/migration.sql, libs/prisma-service/prisma/schema.prisma
Restructured the code to create a Tenant Creation API.
- Enhance code readability and maintainability.
- Improve performance and optimize resource utilization.
- Align with best practices for API design.
- Reorganized and optimized the existing codebase for the Tenant Creation API.
- Addressed code smells and improved overall code quality.
- Verified changes through thorough testing to ensure functionality remains intact.
- Documented the refactoring process for better transparency and understanding.
=> refactor: API create tenant

apps/api-gateway/src/authz/authz.controller.ts, apps/api-gateway/src/authz/authz.service.ts, apps/api-gateway/src/dtos/email-validator.dto.ts, apps/api-gateway/src/user/dto/add-user.dto.ts, apps/api-gateway/src/user/dto/create-user.dto.ts, apps/api-gateway/src/user/dto/email-verify.dto.ts, apps/api-gateway/src/user/dto/login-user.dto.ts, apps/user/interfaces/user.interface.ts, apps/user/src/user.controller.ts, apps/user/src/user.service.ts, libs/common/src/interfaces/user.interface.ts, libs/common/src/response-messages/index.ts
- Refactored following APIs:
1. POST API `/auth/signup` Register new user to platform
2. POST  API`/auth/signin` Authenticate user for the access
1. Implemented a well-defined interface by replacing previous existing `Promise<object>`.
4. Ensured consistency of API status codes.
5. Modified the NATS function.
6. Tested with both positive and negative scenarios.
1. Replaced the return type with a well-defined interface to enhance code clarity.
2. Checked and standardized API status codes to ensure a uniform response.
3. Modified the NATS function to accommodate the adjustments made in the API.
1. The implementation of a well-defined interface enhances code readability and makes the structure of the API response more explicit.
2. Ensuring consistent API status codes improves communication …
=> Refactor sign in and sign up api

apps/agent-provisioning/AFJ/scripts/start_agent_ecs.sh
Create a new folder in your project structure to manage tokens. Tokens are often used for authentication or authorization purposes.
- Organization: Grouping tokens in a dedicated folder enhances project organization and makes it easier to manage authentication-related files.
- Security: Separating tokens from other code files can improve security by minimizing the risk of accidental exposure.
- Store tokens securely, avoiding hardcoding them directly into source code.
- Consider using environment variables or configuration files to manage and load tokens dynamically.
=> Create token folder for the agent

Dockerfiles/Dockerfile.agnet-provisioning, apps/agent-provisioning/AFJ/scripts/start_agent_ecs.sh, apps/agent-provisioning/src/agent-provisioning.service.ts
Create a random service name within the shell script. It eliminates unnecessary parameters related to agent provisioning.
The current script includes unceremonious parameters and agent-provisioning, which are redundant and can lead to issues. This fix aims to streamline the script by removing these unnecessary elements.
Script to generate a random service name without the need for explicit parameters and eliminating the agent-provisioning code. The updated script is designed to improve simplicity and efficiency.
=> fix: create service name random in shell script

apps/agent-provisioning/AFJ/scripts/start_agent.sh, apps/agent-provisioning/src/agent-provisioning.service.ts, apps/agent-service/src/repositories/agent-service.repository.ts, apps/connection/src/connection.service.ts
Resolves the agent spin-up issue by implementing a crucial apiKey update in the org_agent table.
The agent spin-up problem was identified to be linked to outdated API keys stored in the org_agent table. This update aims to ensure that the API keys are consistently updated, thus eliminating the spin-up issue.
The update involves making necessary modifications to the org_agent table, ensuring that the apiKey field is updated appropriately during the agent spin-up process. This will result in improved functionality and a more reliable agent deployment process.
=> fix: solved the agent spin-up with apiKey updation on org_agent table

apps/api-gateway/src/dtos/email-validator.dto.ts, apps/api-gateway/src/user/dto/login-user.dto.ts, apps/user/interfaces/user.interface.ts, apps/user/repositories/user.repository.ts, apps/user/src/user.service.ts, libs/common/src/response-messages/index.ts
- Update response for an unregistered, verified email while fetching user details.
- Populate only necessary fields in the API response.
- Handled error responses and status codes.
=> refactor: get user details API

apps/agent-service/src/agent-service.service.ts
Removal of an unnecessary logger from the agent-service module.
The logger in the agent-service module was unnecessary, and its presence could potentially lead to confusion and unnecessary resource consumption. This removal streamlines the codebase and improves overall code clarity.
The unnecessary logger has been identified and safely removed from the agent-service module. The changes have been thoroughly tested to ensure that the removal does not impact the functionality of the module adversely.
=> fix: removed the unnecessary logger from the agent-service module

apps/api-gateway/src/authz/guards/org-roles.guard.ts, apps/api-gateway/src/organization/organization.controller.ts, apps/api-gateway/src/organization/organization.service.ts, apps/organization/interfaces/organization.interface.ts, apps/organization/repositories/organization.repository.ts, apps/organization/src/organization.controller.ts, apps/organization/src/organization.service.ts, libs/common/src/interfaces/organization.interface.ts, libs/common/src/response-messages/index.ts
Refactored following APIs from organization module:
- GET `/orgs/public-profiles/{orgSlug}` Fetch organization details.
- GET `/orgs/dashboard/{orgId}` Get dashboard details.
- GET `/orgs/{orgId}` Get an organization.
- Ensured consistency of API status codes.
- Handled error and success messages.
- Tested with both positive and negative scenarios.
- Ensuring consistent API status codes improves communication between different components of the system and enhances overall reliability.
=> refactor: organization profile APIs

apps/api-gateway/src/authz/guards/ecosystem-roles.guard.ts, apps/api-gateway/src/ecosystem/dtos/create-ecosystem-dto.ts, apps/api-gateway/src/ecosystem/ecosystem.controller.ts, apps/api-gateway/src/ecosystem/ecosystem.service.ts, apps/api-gateway/src/organization/dtos/get-all-organizations.dto.ts, apps/api-gateway/src/organization/dtos/send-invitation.dto.ts, apps/api-gateway/src/organization/dtos/update-organization-dto.ts, apps/api-gateway/src/organization/organization.controller.ts, apps/ecosystem/interfaces/ecosystem.interfaces.ts, apps/ecosystem/src/ecosystem.controller.ts, apps/ecosystem/src/ecosystem.service.ts, libs/common/src/response-messages/index.ts, libs/prisma-service/prisma/migrations/20240112134257_ecosystem_tags_optional/migration.sql, libs/prisma-service/prisma/schema.prisma
Refactored following APIs from organization module:
GET `/ecosystem/{orgId}` Get all organization ecosystems.
POST `/ecosystem/{orgId}` Create a new ecosystem.
GET `/ecosystem/{ecosystemId}/{orgId}/dashboard` Get ecosystem dashboard details
PUT `/ecosystem/{ecosystemId}/{orgId}` Edit ecosystem
- Ensured consistency of API status codes.
- Handled error and success messages.
- Tested with both positive and negative scenarios.
- Ensuring consistent API status codes improves communication between different components of the system and enhances overall reliability.
=> refactor: create ecosystem and get ecosystem APIs

apps/ecosystem/templates/EcosystemInviteTemplate.ts, apps/organization/templates/organization-invitation.template.ts, apps/user/templates/user-email-template.ts, apps/verification/templates/out-of-band-verification.template.ts
- Fixed background css issue for email templates.
=> fix: email template background css

apps/api-gateway/src/credential-definition/credential-definition.controller.ts, apps/api-gateway/src/credential-definition/credential-definition.service.ts, apps/ledger/src/credential-definition/credential-definition.service.ts
- Refactored POST API response of send cred def of ledger
=> fix: POST API response of send cred def to ledger

libs/prisma-service/prisma/seed.ts
- Prevent Appending Data in Prisma When Re-seeding for Master Record
- When re-seeding data for a master record in Prisma, it is essential to ensure that the process does not append duplicate data. Appending data can lead to inconsistencies, redundancy, and potential issues in the application's functionality. 
To address this issue, follow these steps:
- Identification of Master Record:
Identify the master record for which re-seeding is being performed. This is typically a record that serves as a primary reference point in the database.
- Data Check:
Before re-seeding, implement a check to verify if the data already exists for the identified master record. This can be done by querying the database using Prisma to check for existing data associated with the master record.
- Conditional …
=> fix: re-seeding should not append the data in master table

apps/api-gateway/src/authz/jwt.strategy.ts
- Refactored key value for `client_id` in jwt strategy
=> refactor: Client auth register

apps/api-gateway/src/authz/guards/org-roles.guard.ts, libs/common/src/response-messages/index.ts
- Refactored user-friendly message if a user attempts to access an API that is inaccessible to their role
- Updated message to "User does not have access"
- Previously user got an "Forbidden Resource" message which is not user-friendly.
- Added condition in `UserRoleGuard`. So that it will reflect for all the APIs.
=> fix: user-friendly message if user not have access

apps/user/interfaces/user.interface.ts, apps/user/src/user.service.ts
- Worked on the passkey fixes for keycloak reset password registration.
=> fix: Passkey fixes

apps/api-gateway/src/authz/socket.gateway.ts, apps/api-gateway/src/interfaces/ISocket.interface.ts, apps/issuance/src/issuance.service.ts
Updated socket responses for bulk issuance.
Requires `fileUploadId` to check the history of recently processed issuance.
=> fix: socket response for bulk issuance

apps/api-gateway/src/authz/jwt.strategy.ts, libs/common/src/response-messages/index.ts
Updated unauthorized error message when a user tries to use API with the invalid access token
Previous response:
```
{
"statusCode": 500,
"message": "Cannot read properties of null (reading 'iss')",
"error": "Internal Server error"
}
```
Refactored response:
```
{
"statusCode": 401,
"message": "Invalid access token",
"error": "Unauthorized"
}
```
If an unauthorized user tries to access API then it should return a proper error message.
=> fix: unauthorized error message

apps/api-gateway/src/issuance/dtos/issuance.dto.ts, apps/api-gateway/src/issuance/issuance.controller.ts, apps/api-gateway/src/issuance/issuance.service.ts, apps/issuance/interfaces/issuance.interfaces.ts, apps/issuance/src/issuance.controller.ts, apps/issuance/src/issuance.service.ts
- Implemented selective bulk issuance functionality.
- Resolved upload file issue .
=> feat: selective bulk issuance

apps/api-gateway/src/dtos/create-schema.dto.ts, apps/api-gateway/src/ecosystem/dtos/request-schema.dto.ts, apps/api-gateway/src/issuance/dtos/issuance.dto.ts, apps/issuance/interfaces/issuance.interfaces.ts, apps/issuance/src/issuance.service.ts, apps/ledger/src/schema/interfaces/schema-payload.interface.ts, apps/ledger/src/schema/schema.service.ts, libs/common/src/response-messages/index.ts
- Added `isRequired` field in create schema API in schema service.
- Done changes in dto validations for following APIs:-
1.   POST `/orgs/{orgId}/credentials/offer` Issuer create a credential offer
2.   POST `/orgs/{orgId}/credentials/oob/email` Creates a out-of-band credential offer and sends them via emails
3.   POST `/orgs/{orgId}/credentials/oob/offer` Create out-of-band credential offer
- Added `isRequired` field in request endorsement API in ecosystem service.
=> feat: required attributes in create schema API

apps/api-gateway/src/authz/guards/ecosystem-roles.guard.ts
- Updated error message if the user does not have access to call an API.
- Updated message from "Forbidden resource" to "User does not have access".
To provide user-friendly message
=> fix: user friendly message of ecosystem roles if user does not have access

apps/api-gateway/src/authz/guards/ecosystem-roles.guard.ts, apps/api-gateway/src/ecosystem/dtos/get-members.dto.ts, apps/api-gateway/src/ecosystem/ecosystem.controller.ts, apps/api-gateway/src/ecosystem/ecosystem.service.ts, apps/ecosystem/interfaces/ecosystemMembers.interface.ts, apps/ecosystem/src/ecosystem.controller.ts, apps/ecosystem/src/ecosystem.repository.ts, apps/ecosystem/src/ecosystem.service.ts, libs/common/src/response-messages/index.ts, libs/enum/src/enum.ts, libs/http-exception.filter.ts
- Resolved the issue of searching and sorting
- Updated query to sort value as per the column name
- On the studio side, search and sort should work as expected to improve user accessibility for the records
=> fix: ecosystem member list search sorting issue

apps/api-gateway/src/issuance/issuance.controller.ts, apps/issuance/src/issuance.service.ts
- Worked on the error response handling in the bulk issuance upload
=> fixed: bulk issuance upload issue

apps/api-gateway/src/dtos/create-schema.dto.ts, apps/api-gateway/src/ecosystem/dtos/request-schema.dto.ts, apps/api-gateway/src/verification/dto/request-proof.dto.ts, apps/verification/src/interfaces/verification.interface.ts, apps/verification/src/verification.service.ts
- Fixed issue of attributeNames in proof request API.
=> fix: multiple attributes in proof request fixes

Dockerfiles/Dockerfile.agent-provisioning, Dockerfiles/Dockerfile.agent-service, apps/agent-provisioning/AFJ/scripts/docker_start_agent.sh, docker-compose.yml
Resolves the issue related to agent spinup when initiating the agent-provisioning service with Dockerization.
The agent-provisioning service was experiencing difficulties in spinup when started with Dockerization. This PR aims to rectify the problem and ensure a smooth agent spinup process within the Dockerized environment.
The fix involves making necessary adjustments and optimizations in the codebase to facilitate proper agent spinup when deploying the agent-provisioning service with Docker. This includes addressing any dependencies or configurations that were causing the spinup issue. The changes implemented in this PR are designed to enhance the overall functionality and reliability of the agent-provisioning service in a Dockerized environment.
=> fix: resolve agent spin-up issue in agent-provisioning service with dockerization

apps/api-gateway/src/agent-service/dto/create-tenant.dto.ts
Resolved the issue related to the ledgerId restriction when passed as a string of an array.
The existing implementation did not handle the ledgerId restriction properly when provided as a string within an array. This caused unexpected behavior and potential errors in certain scenarios. The fix ensures that the ledgerId restriction is correctly processed when presented in this format.
Modified the relevant function to correctly parse and handle ledgerId when passed as a string within an array.
Added test cases to cover the scenarios where the issue was identified.
Updated documentation to reflect the corrected behavior and provide examples of using ledgerId in this specific format.
=> fix: solved issue for the ledgerId restriction as a string of array

apps/api-gateway/src/issuance/issuance.controller.ts, apps/api-gateway/src/verification/verification.controller.ts, apps/ecosystem/src/ecosystem.repository.ts, apps/ecosystem/src/ecosystem.service.ts, apps/ledger/src/credential-definition/credential-definition.service.ts, apps/verification/src/verification.service.ts, libs/client-registration/src/client-registration.service.ts
- Fixed issue:- Incorrect message displayed when submitting schema with the same name and version that is already submitted on ledger (Endorsement flow).
-  Removed unnecessary logs from issuance and verification services.
=> fix: error handling for endorsement flow

apps/agent-provisioning/AFJ/scripts/start_agent.sh, apps/issuance/interfaces/issuance.interfaces.ts, apps/issuance/src/issuance.service.ts
- Solved bulk issuance when upload csv and issue the credentials
=> fix: solved bulk issuance and with email issuance flow 

apps/organization/repositories/organization.repository.ts, apps/organization/src/organization.service.ts, apps/user/src/user.service.ts, libs/common/src/response-messages/index.ts
- Fixed validation on org create when org slug matches.
- Refactor the user and org client login validations.
=> fix: org client validations & org create validations

apps/issuance/src/issuance.service.ts
Refactor and fix the issuance return data in the out-of-band (OOB) functionality.
The current implementation of the issuance return data in the OOB functionality contains errors and needs restructuring for better clarity and reliability. Enhance the code to ensure accurate and consistent return data, improving the overall functionality of the system.
Refactoring of the streamline the issuance return data process. By addressing identified issues and optimizing the code
=> Refactor and correct issuance return data in OOB functionality

apps/api-gateway/src/authz/guards/org-roles.guard.ts, apps/api-gateway/src/authz/guards/user-access-guard.ts, apps/api-gateway/src/organization/organization.controller.ts, apps/api-gateway/src/organization/organization.service.ts, apps/api-gateway/src/user/user.controller.ts, apps/organization/dtos/update-invitation.dt.ts, apps/organization/repositories/organization.repository.ts, apps/organization/src/organization.controller.ts, apps/organization/src/organization.service.ts, apps/user/interfaces/user.interface.ts, apps/user/repositories/user.repository.ts, apps/user/src/user.controller.ts, apps/user/src/user.service.ts, libs/client-registration/src/client-registration.service.ts, libs/client-registration/src/interfaces/client.interface.ts, libs/common/src/common.service.ts, libs/common/src/response-messages/index.ts, libs/keycloak-url/src/keycloak-url.service.ts, libs/org-roles/interfaces/org-roles.interface.ts, libs/prisma-service/prisma/migrations/20240220121359_user_org_idproleid/migration.sql, libs/prisma-service/prisma/schema.prisma, libs/user-org-roles/repositories/index.ts, libs/user-org-roles/src/user-org-roles.service.ts
- User Registration in Keycloak.
- Create client for `org` and roles associated with it on keycloak.
- Organization invitation sent for client roles and accepted as well from other user's side.
- Update Organization client user roles
- Refactored `orgRoleGuard`.
=> feat: Keycloak user role org map

apps/agent-service/src/agent-service.controller.ts, apps/agent-service/src/agent-service.service.ts, apps/api-gateway/src/connection/connection.controller.ts, apps/api-gateway/src/connection/connection.service.ts, apps/api-gateway/src/connection/dtos/get-all-connections.dto.ts, apps/api-gateway/src/interfaces/IConnectionSearch.interface.ts, apps/connection/src/connection.controller.ts, apps/connection/src/connection.service.ts, apps/connection/src/interfaces/connection.interfaces.ts, libs/common/src/interfaces/agent-service.interface.ts
- Connection list from agent
- Added `recordId` in create connection
- In Platform we are only storing the connection details for the webhook
=> fix: connection list from agent

libs/prisma-service/prisma/data/credebl-master-table.json
- Refactored JSON data for both the ledgerConfig and ledgers table
=> fix: refactored tables

apps/api-gateway/src/authz/authz.controller.ts, apps/api-gateway/src/authz/authz.service.ts, apps/api-gateway/src/authz/dtos/refresh-token.dto.ts, apps/user/src/user.controller.ts, apps/user/src/user.service.ts, libs/client-registration/src/client-registration.service.ts, libs/common/src/response-messages/index.ts
- Implemented POST API of `/auth/refresh-token` to get the `access_token` from the `refresh_token`
- To get the updated  `access_token` if current is `expired`
=> feat: Auth refresh token

apps/api-gateway/src/organization/organization.controller.ts
- Restricted client access to update org and create client credentials
- To set org related APIs access to client credentials
=> fix: client credentials access

apps/api-gateway/src/credential-definition/credential-definition.controller.ts, apps/api-gateway/src/credential-definition/credential-definition.service.ts, apps/api-gateway/src/credential-definition/dto/create-cred-defs.dto.ts, apps/api-gateway/src/credential-definition/interfaces/index.ts, apps/ledger/src/credential-definition/credential-definition.controller.ts, apps/ledger/src/credential-definition/credential-definition.service.ts, apps/ledger/src/credential-definition/repositories/credential-definition.repository.ts, libs/common/src/interfaces/cred-def.interface.ts
- Modify GET API of `/orgs/{orgId}/cred-defs/{credDefId}` (get an existing cred def by id).
- Modify GET API of `/verification/cred-defs/{schemaId}` (get an existing cred def by schema id).
- Modify GET API of `/orgs/{orgId}/cred-defs` (get all cred-defs of provided org id with pagination).
- Modify GET API of `/orgs/{orgId}/bulk/cred-defs` (fetch all cred-defs for bulk operation).
- Modify  POST API of `/orgs/{orgId}/cred-defs` (create and sends a cred-def to the ledger).
1.Checked validations on payload.
2.Refactor response
3.Ensured consistency of API status codes.
4.Modified the NATS function.
- The implementation of a well-defined interface enhances code readability and makes the structure of the API response more explicit.
- Ensuring consistent API status codes improves …
=> refactor: cred-def controller APIs

apps/api-gateway/src/agent-service/agent-service.controller.ts, apps/api-gateway/src/agent-service/dto/create-did.dto.ts, apps/api-gateway/src/agent-service/dto/create-new-did.dto.ts
- `isPrimaryDid` parameter was implemented in `createDidDto`
- Created one new DTO for `isPrimaryDid` and extended the property of  `createDidDto`
=> fix: wallet creation DTO issue

apps/api-gateway/src/verification/dto/request-proof.dto.ts
##What
Added a missing attribute `name` in presentationDefinition payload. This is a shared attributes between the verifier and prover addition to the requested data attributes.
##Why
To be aligned with the standard specification.
=> Update presentation definition payload of W3C request

apps/api-gateway/src/dtos/send-proof-request.dto.ts, apps/api-gateway/src/issuance/dtos/issuance.dto.ts
##What
Applied validation on Credential definition only if credentialType is Indy. As for JSONLD credentials it is not required
=> fix: DTO validation

apps/agent-service/src/agent-service.service.ts, apps/api-gateway/src/connection/connection.controller.ts, apps/api-gateway/src/connection/connection.service.ts, apps/api-gateway/src/connection/dtos/connection.dto.ts, apps/connection/src/connection.controller.ts, apps/connection/src/connection.service.ts, apps/connection/src/interfaces/connection.interfaces.ts, apps/organization/src/organization.service.ts
Remove the legacy connection invitation feature from the codebase.
The legacy connection invitation feature is no longer necessary.
Removes all code related to the legacy connection invitation feature
=> refactor: remove legacy connection invitation

apps/api-gateway/src/connection/dtos/connection.dto.ts, apps/connection/src/connection.repository.ts, apps/connection/src/connection.service.ts, apps/connection/src/interfaces/connection.interfaces.ts, apps/issuance/src/issuance.repository.ts, apps/issuance/src/issuance.service.ts, apps/verification/src/interfaces/verification.interface.ts, apps/verification/src/repositories/verification.repository.ts, apps/verification/src/verification.service.ts, libs/common/src/interfaces/agent-service.interface.ts, libs/common/src/interfaces/connection.interface.ts, libs/prisma-service/prisma/migrations/20240430114046_add_invitation_did/migration.sql, libs/prisma-service/prisma/schema.prisma
- Add invitation did while creating invitation
- To add reuse connection functionality
=> feat:add-invitation-did-for-reuse-connection

apps/api-gateway/src/credential-definition/dto/get-all-platform-cred-defs.dto.ts, apps/api-gateway/src/platform/platform.controller.ts, apps/api-gateway/src/platform/platform.service.ts, apps/api-gateway/src/schema/dtos/get-all-schema.dto.ts, apps/api-gateway/src/schema/schema.controller.ts, apps/ledger/src/credential-definition/credential-definition.controller.ts, apps/ledger/src/credential-definition/credential-definition.service.ts, apps/ledger/src/credential-definition/interfaces/create-credential-definition.interface.ts, apps/ledger/src/credential-definition/repositories/credential-definition.repository.ts, apps/ledger/src/schema/enum/schema.enum.ts, libs/common/src/dtos/pagination.dto.ts, libs/common/src/interfaces/cred-def.interface.ts, libs/enum/src/enum.ts
- Developed GET API for fetching all credential definitions from platform
- To fetch credential definitions list from platform
=> feat: fetch all credential definitions from platform

apps/agent-service/src/agent-service.service.ts, apps/api-gateway/src/organization/organization.controller.ts, apps/organization/interfaces/organization.interface.ts, apps/organization/repositories/organization.repository.ts, apps/organization/src/organization.service.ts
- Fixed store did document issue while creating did
- Removed data from set primary did API
- Added did document in `org_agent` while changing primary did
=> fix: store did document while creating did

apps/agent-provisioning/AFJ/scripts/start_agent.sh, apps/agent-provisioning/src/agent-provisioning.service.ts, apps/api-gateway/src/schema/schema.controller.ts, apps/api-gateway/src/schema/schema.service.ts, apps/ecosystem/interfaces/ecosystem.interfaces.ts, apps/ecosystem/src/ecosystem.repository.ts, apps/ecosystem/src/ecosystem.service.ts, apps/ledger/src/schema/enum/schema.enum.ts, apps/ledger/src/schema/interfaces/schema-payload.interface.ts, apps/ledger/src/schema/repositories/schema.repository.ts, apps/ledger/src/schema/schema.controller.ts, apps/ledger/src/schema/schema.interface.ts, apps/ledger/src/schema/schema.service.ts, libs/common/src/interfaces/schema.interface.ts, libs/common/src/response-messages/index.ts, libs/enum/src/enum.ts, libs/prisma-service/prisma/migrations/20240514051441_added_type_in_schema/migration.sql, libs/prisma-service/prisma/schema.prisma
- Added schema URL in the schema response
- Implemented store W3C schema in the database
=> fix/feat : Updated W3C schema response and Implemented schema store logic

apps/api-gateway/src/app.module.ts, apps/issuance/src/issuance.module.ts, apps/issuance/src/issuance.processor.ts, apps/issuance/src/issuance.service.ts
- Added nest queue for bulk issuance implementation
=> feat: bulk issuance implementation using nest queue

apps/issuance/src/issuance.service.ts
- Fixes invalid response inside response for oob issuance
- Previous response included response inside a response object
Fixes: [#406](https://github.com/credebl/automation-test-suite/issues/406)
=> fix: Invalid nested response

apps/agent-service/src/agent-service.service.ts, apps/agent-service/src/interface/agent-service.interface.ts, apps/agent-service/src/repositories/agent-service.repository.ts, apps/api-gateway/src/organization/organization.controller.ts, apps/organization/src/organization.service.ts, libs/common/src/response-messages/index.ts
This fix ensures that when a new DID (Decentralized Identifier) is created and marked as the primary DID, all other existing DIDs for that user are updated to not be the primary DID.
Ensuring only one DID is marked as primary per user.
- Modify the code to set the primary DID correctly: Update the relevant part of the codebase where DIDs are created or updated to ensure only one DID is marked as primary.
- Update other DIDs: Implement logic to update all other DIDs to not be primary when a new primary DID is set.
=> fix: set primary DID for new DID

apps/organization/repositories/organization.repository.ts, apps/organization/src/organization.controller.ts, apps/organization/src/organization.service.ts, apps/user/src/user.service.ts, libs/common/src/response-messages/index.ts
- Changes in POST `/orgs` Create a new Organization API. Implemented logic to restricted user to create more than 10 organizations.
- Changes in POST `/users/org-invitations/{invitationId}` accept/reject organization invitation API. Implemented logic to restrict user for accepting organization invitation if user is already associated with 10 organziations
=> feat: limit 10 organizations per user

apps/agent-service/src/agent-service.service.ts, apps/agent-service/src/repositories/agent-service.repository.ts
- Update the org_agent table to reflect the DID Doc when a DID is set as a primary by a dedicated agent.
- To maintain accurate and up-to-date information in the org_agent table.
- To ensure that the primary DID status is correctly represented, which is crucial for organizational operations and integrations.
- Modify the logic in the agent's code to trigger an update in the org_agent table when a DID is set as a primary.
- Add a database query to update the DID Doc in the org_agent table based on the dedicated agent's action.
=> fix: update DID Doc by dedicated agent

apps/issuance/interfaces/issuance.interfaces.ts, apps/issuance/src/issuance.processor.ts, apps/issuance/src/issuance.service.ts, libs/common/src/response-messages/index.ts
- Async queue implementation
- Added counter to get the number of iteration
=> feat: async queue implementation

apps/agent-service/src/agent-service.controller.ts, apps/agent-service/src/agent-service.module.ts, apps/agent-service/src/agent-service.service.ts, apps/agent-service/src/repositories/agent-service.repository.ts, apps/api-gateway/src/organization/organization.controller.ts, apps/api-gateway/src/organization/organization.service.ts, apps/organization/repositories/organization.repository.ts, apps/organization/src/organization.controller.ts, apps/organization/src/organization.module.ts, apps/organization/src/organization.service.ts, apps/user/interfaces/user.interface.ts, apps/user/repositories/user.repository.ts, apps/user/src/user.controller.ts, apps/user/src/user.service.ts, libs/common/src/response-messages/index.ts, libs/enum/src/enum.ts, libs/http-exception.filter.ts, libs/prisma-service/prisma/migrations/20240610111750_added_email_user_org_delete_activity/migration.sql, libs/prisma-service/prisma/migrations/20240610142316_remove_unique_user_id_user_org_delete_activity/migration.sql, libs/prisma-service/prisma/schema.prisma, libs/user-activity/repositories/index.ts
Added a new function to handle deleted metadata and stored matadata to the table.
To efficiently manage and track metadata that has been deleted.
- Implemented a function to log and manage deleted metadata entries.
- Created a new database table to store details of deleted metadata.
=> feat: added deleted metadata function and table

libs/prisma-service/prisma/migrations/20240611134959_added_null_user_org_delete_activity/migration.sql, libs/prisma-service/prisma/schema.prisma
Addition of an empty string in the user_org_delete_activity table.
The empty string addition is essential for maintaining data integrity and ensuring compatibility with existing database structures. It helps in accommodating scenarios where certain fields may not have specific values but still require placeholders.
The addition of the empty string is implemented by modifying the schema definition or updating relevant SQL scripts to include the appropriate default value for the respective column in the user_org_delete_activity table. Additionally, any necessary documentation updates or test cases should be included to reflect this change accurately.
=> fix: added the empty string in user_org_delete_activity table

apps/api-gateway/src/organization/dtos/create-organization-dto.ts, apps/organization/dtos/create-organization.dto.ts, apps/organization/repositories/organization.repository.ts, libs/prisma-service/prisma/migrations/20240610133418_added_field_in_org_table/migration.sql, libs/prisma-service/prisma/schema.prisma
- Added fields in org table for saving metadata
=> refactor:org create API

.env.sample, apps/api-gateway/src/verification/dto/request-proof.dto.ts, apps/issuance/src/issuance.service.ts, apps/issuance/templates/out-of-band-issuance.template.ts, apps/verification/src/interfaces/verification.interface.ts, apps/verification/src/verification.service.ts, apps/verification/templates/out-of-band-verification.template.ts, libs/common/src/common.utils.ts
- Add support for deeplink
- To redirect deeplink url to ADEYA
=> fix: add deeplink support

apps/api-gateway/src/organization/organization.controller.ts, apps/api-gateway/src/organization/organization.service.ts, apps/connection/src/connection.controller.ts, apps/connection/src/connection.repository.ts, apps/connection/src/connection.service.ts, apps/ecosystem/src/ecosystem.controller.ts, apps/ecosystem/src/ecosystem.repository.ts, apps/ecosystem/src/ecosystem.service.ts, apps/issuance/src/issuance.controller.ts, apps/issuance/src/issuance.repository.ts, apps/issuance/src/issuance.service.ts, apps/organization/repositories/organization.repository.ts, apps/organization/src/organization.controller.ts, apps/organization/src/organization.service.ts, apps/verification/src/repositories/verification.repository.ts, apps/verification/src/verification.controller.ts, apps/verification/src/verification.service.ts, libs/common/src/interfaces/organization.interface.ts, libs/common/src/response-messages/index.ts
1). Implemented API to fetch organization activity count
- Implemented function to get verification records count
- Implemented function to get issuance records count
- Implemented function to get connection records count
- Implemented function to get organization invitations count
- Implemented function to get organization ecosystems count
- Implemented function to get organization users count
- Implementing an API to fetch organization activity count allows for tracking various actions within an organization
=> feat: fetch org activity count

apps/issuance/templates/out-of-band-issuance.template.ts, apps/verification/templates/out-of-band-verification.template.ts
- Change email templates for Issuance and Verification 
- Change in CTA in email for issuance and verification based on screen resolution
=> Refactor: add screen based email template change

apps/api-gateway/src/utilities/dtos/shortening-url.dto.ts, apps/api-gateway/src/utilities/utilities.controller.ts, apps/api-gateway/src/utilities/utilities.service.ts, libs/enum/src/enum.ts
Enable storing object from api-gateway
=> fix: enable storing object from api-gateway

apps/api-gateway/src/organization/organization.controller.ts, apps/api-gateway/src/organization/organization.service.ts, apps/api-gateway/src/user/dto/add-user.dto.ts, apps/api-gateway/src/user/dto/create-user.dto.ts, apps/organization/repositories/organization.repository.ts, apps/organization/src/organization.controller.ts, apps/organization/src/organization.service.ts, apps/user/interfaces/user.interface.ts, apps/user/repositories/user.repository.ts, apps/user/src/user.service.ts, apps/user/templates/user-email-template.ts, libs/client-registration/src/client-registration.service.ts, libs/common/src/interfaces/user.interface.ts, libs/common/src/response-messages/index.ts
- Adding new columns to the user table for storing Keycloak clientId and client secret.
- Implementing the logic to update and retrieve these values when creating or updating a user.
- Modifying the necessary services and controllers to handle the new fields.
- Managing Keycloak clientId and client secret directly on the user table is necessary to:
Simplify the integration between our application and Keycloak by having the authentication details directly associated with the user.
- Update user creation and update services to include ClientId and Client Secret fields.
- Modify the relevant controllers to accept and process these fields in user-related requests.
=> feat: keycloak clientId and client secret manage on the user table

apps/agent-service/src/agent-service.service.ts, apps/agent-service/src/interface/agent-service.interface.ts, apps/agent-service/src/repositories/agent-service.repository.ts, apps/organization/interfaces/organization.interface.ts, apps/organization/repositories/organization.repository.ts, apps/organization/src/organization.service.ts, libs/common/src/response-messages/index.ts, libs/enum/src/enum.ts, libs/prisma-service/prisma/data/credebl-master-table.json
- Implemented validation logic to ensure network and ledgerId are correctly updated when a DID is updated.
- Previously, there was no validation in place for network and ledgerId during a DID update. This could lead to inconsistencies and potential issues with the integrity of the data.
- Added validation checks in the update function for DIDs.
- Modified the update process to include conditions that check the validity of the network and ledgerId.
- Updated relevant tests to cover scenarios where the network and ledgerId are updated to ensure they pass the new validation rules.
=> fix: added validation for network and ledgerId update when did update

apps/organization/src/organization.service.ts
- Modify the logic to fetch clientId and client secret using userId.
- To ensure that authentication details are correctly retrieved based on the user's unique identifier.
- Updated the relevant functions to query the database using userId to get clientId and client secret.
- Refactored the authentication module to incorporate the new logic.
- Added tests to verify that clientId and client secret are correctly fetched by userId.
=> fix: fetch clientId and client secret by userId

apps/agent-service/src/repositories/agent-service.repository.ts, apps/api-gateway/src/agent-service/agent-service.controller.ts, apps/api-gateway/src/organization/organization.controller.ts, apps/ledger/src/schema/repositories/schema.repository.ts, apps/organization/repositories/organization.repository.ts, apps/user/src/user.service.ts, libs/enum/src/enum.ts, libs/prisma-service/prisma/migrations/20240619102525_add_cascade_delete/migration.sql, libs/prisma-service/prisma/migrations/20240619103315_allow_null_organization_id/migration.sql, libs/prisma-service/prisma/schema.prisma
- Improved the validation logic for deleting a wallet, ensuring that references in related tables are properly checked.
- Added validation to ensure orgId is null or not in schema and credential definition entities.
- To prevent accidental deletion of wallets that are still referenced in other parts of the database, which could lead to data integrity issues.
- To ensure that orgId is always present in schema and credential definition entities, null reference as an optional.
- Implemented additional validation checks before allowing the deletion of a wallet, ensuring no existing references are left in related tables.
- Added validation rules in the schema and credential definition code to enforce that orgId null as an optional
=> fix: enhance wallet deletion validation and add null check for orgId in schema and credential-definition

apps/agent-service/src/agent-service.service.ts
- Added the validation for create DID when ledgerId is null
- When ledgerId is null, DID does not create with a specific ledger
=> fix: add condition to check ledgerId is not null

apps/api-gateway/src/organization/organization.controller.ts, apps/organization/interfaces/organization.interface.ts, apps/organization/repositories/organization.repository.ts, apps/organization/src/organization.service.ts, apps/organization/templates/delete-organization-invitations.template.ts, apps/user/interfaces/user.interface.ts, apps/user/repositories/user.repository.ts, apps/user/src/user.controller.ts, apps/user/src/user.service.ts, libs/client-registration/src/client-registration.service.ts, libs/enum/src/enum.ts
- Added functionality to send an email notification when an organization invitation is deleted.
- To ensure that both the inviter and invitee are informed about the deletion of the invitation.
- Implemented a service to handle email notifications specifically for deleted invitations.
- Updated the orgController to trigger the email notification upon deletion of an invitation.
- Updated email templates to include relevant information about the deleted invitation.
=> feat: send email for delete organization invitations

apps/agent-service/src/agent-service.service.ts, libs/common/src/response-messages/index.ts
Added validation for the delete wallet functionality and performed an initial check on the record for deleting the wallet.
To ensure that the wallet deletion process includes necessary validations and checks, thereby maintaining data integrity and preventing errors during the deletion process.
- Added a validation step to check if the wallet exists before attempting deletion.
- Updated the `deleteWallet` function to include a check for the wallet record.
- Wrapped the delete operations in a Prisma transaction to ensure rollback in case of errors.
=> fix: added the validation for the delete wallet and first check on the record for delete wallet

apps/agent-service/src/agent-service.service.ts, apps/api-gateway/src/dtos/create-schema.dto.ts, apps/api-gateway/src/schema/schema.controller.ts, apps/api-gateway/src/schema/schema.service.ts, apps/ledger/src/schema/enum/schema.enum.ts, apps/ledger/src/schema/interfaces/schema-payload.interface.ts, apps/ledger/src/schema/interfaces/schema.interface.ts, apps/ledger/src/schema/schema.controller.ts, apps/ledger/src/schema/schema.service.ts, libs/common/src/cast.helper.ts, libs/common/src/common.utils.ts, libs/common/src/response-messages/index.ts, libs/enum/src/enum.ts
- Supported schema for key and web
- Insufficient balance implementation
- Implement a single endpoint for schema creation for all type of schemas
=> feat: support schema for key and web

apps/api-gateway/src/organization/dtos/create-organization-dto.ts
- changed CreateOrganizationDto class as required.
For creating new organisation we required geo-location related attribute as optional.
=> feat: added geolocation APIs in CREDEBL.

apps/api-gateway/src/schema/schema.controller.ts, apps/ledger/src/schema/repositories/schema.repository.ts, apps/ledger/src/schema/schema.service.ts
- Get w3c schemas by schema Id
- To fetch W3C type schema details BY schemaId
=> feat: get w3c schema details by schema id

apps/api-gateway/src/schema/schema.controller.ts, apps/ledger/src/schema/repositories/schema.repository.ts, apps/ledger/src/schema/schema.service.ts
- Refactored response for get schemas by orgId response.
=> refactor: get schemas by orgId response

apps/user/src/user.service.ts
- Resolved below issue:
When an error occurs while sending the verification email and the same issue persists upon retrying, the response states that the verification email has already been sent.
- To prevent incorrect state and misleading error messages
=> fix: send email verification issue

apps/api-gateway/src/dtos/create-schema.dto.ts, apps/ledger/src/credential-definition/credential-definition.service.ts, apps/ledger/src/credential-definition/interfaces/index.ts, apps/ledger/src/credential-definition/repositories/credential-definition.repository.ts, apps/ledger/src/schema/repositories/schema.repository.ts, apps/ledger/src/schema/schema.service.ts
- Removed logic to check schema already exists for W3C
- Changed template list response
- Added validation for empty attribute
=> refactor: bulk issuance template list response changes

apps/api-gateway/src/issuance/dtos/issuance.dto.ts, apps/api-gateway/src/issuance/issuance.controller.ts, apps/issuance/interfaces/issuance.interfaces.ts, apps/issuance/src/issuance.service.ts, apps/issuance/templates/out-of-band-issuance.template.ts
- Added 'organizationLogoUrl' and 'platformName' in request parameter for issue-bulk-credentials API.
- Refactored issue-bulk-credentials API for EduCred issuance.
- While issuing credentials for user from EduCred side need to send issuance email which is specific to EduCred.
- Tested from CREDEBL as well as EduCred Side.
=> feat: added dynamic support to issuance email template. 

apps/api-gateway/src/issuance/issuance.controller.ts, apps/api-gateway/src/issuance/issuance.service.ts, apps/issuance/src/issuance.controller.ts, apps/issuance/src/issuance.service.ts
- Added 'organizationLogoUrl' and 'platformName' in request parameter for issue-bulk-credentials API.
- Refactored retry-bulk-credentials API for issuance.
- While issuing credentials for user need to send issuance email which is specific to organisation.
=> feat:refactored `retry-bulk-credentials` api to add dynamic support to email template

apps/api-gateway/src/authz/guards/org-roles.guard.ts, apps/api-gateway/src/authz/guards/user-role.guard.ts, apps/api-gateway/src/authz/jwt-payload.interface.ts, apps/api-gateway/src/authz/jwt.strategy.ts, apps/api-gateway/src/user/dto/add-user.dto.ts, apps/api-gateway/src/user/user.service.ts, apps/user/interfaces/user.interface.ts, apps/user/src/user.controller.ts, apps/user/src/user.service.ts, libs/client-registration/src/client-registration.service.ts, libs/client-registration/src/dtos/create-user.dto.ts, libs/common/src/common.constant.ts
- Added validation for the organization role guard and user access guard.
- Updated the user decorator for user roles.
- To ensure that only users with the appropriate roles and permissions can access certain functionalities.
- To enhance the security and integrity of the application by enforcing role-based access control.
- Implemented new validation logic for the organization role guard.
- Added checks for user access guard to ensure proper user validation.
- Modified the user decorator to handle user roles more effectively.
=> feat: added holder role guard

apps/api-gateway/src/app.module.ts, apps/api-gateway/src/cloud-wallet/cloud-wallet.controller.ts, apps/api-gateway/src/cloud-wallet/cloud-wallet.module.ts, apps/api-gateway/src/cloud-wallet/cloud-wallet.service.ts, apps/api-gateway/src/cloud-wallet/dtos/cloudWallet.dto.ts, apps/api-gateway/src/cloud-wallet/enums/connections.enum.ts, apps/cloud-wallet/src/cloud-wallet.controller.ts, apps/cloud-wallet/src/cloud-wallet.module.ts, apps/cloud-wallet/src/cloud-wallet.repository.ts, apps/cloud-wallet/src/cloud-wallet.service.ts, apps/cloud-wallet/src/main.ts, apps/cloud-wallet/test/jest-e2e.json, apps/cloud-wallet/tsconfig.app.json, libs/common/src/common.constant.ts, libs/common/src/common.service.ts, libs/common/src/interfaces/cloud-wallet.interface.ts, libs/common/src/response-messages/index.ts, libs/enum/src/enum.ts, libs/prisma-service/prisma/data/credebl-master-table.json, libs/prisma-service/prisma/migrations/20240717074318_cloud_wallet_tables/migration.sql, libs/prisma-service/prisma/migrations/20240717092122_added_agnet_url_and_apikey_in_cloud_wallet_table/migration.sql, libs/prisma-service/prisma/migrations/20240717102514_added_key_in_cloud_wallet_table/migration.sql, libs/prisma-service/prisma/migrations/20240717104549_added_connection_image_in_cloud_wallet_table/migration.sql, libs/prisma-service/prisma/schema.prisma, libs/prisma-service/prisma/seed.ts, nest-cli.json
- Implemented `cloud-wallet` MS
- Added logic to create and store cloud wallet details
=> feat: create cloud wallet

apps/user/interfaces/user.interface.ts, apps/user/repositories/user.repository.ts, apps/user/src/user.service.ts, libs/common/src/response-messages/index.ts, libs/enum/src/enum.ts
Refactor the code to store the holder role in the user role mapping table.
Storing the holder role in a dedicated user role mapping table enhances maintainability, scalability, and clarity in role management.
- Created a new user role mapping table to store user roles.
- Updated the existing code to insert and retrieve holder roles from the new table.
- Modified related functions and queries to accommodate the new structure.
- Added necessary migrations to update the database schema.
=> refactor: store holder role in user role mapping table

apps/api-gateway/src/cloud-wallet/cloud-wallet.controller.ts, apps/api-gateway/src/cloud-wallet/cloud-wallet.service.ts, apps/api-gateway/src/cloud-wallet/dtos/configure-base-wallet.dto.ts, apps/cloud-wallet/interfaces/cloud-wallet.interface.ts, apps/cloud-wallet/src/cloud-wallet.controller.ts, apps/cloud-wallet/src/cloud-wallet.repository.ts, apps/cloud-wallet/src/cloud-wallet.service.ts, libs/common/src/interfaces/cloud-wallet.interface.ts, libs/common/src/response-messages/index.ts, libs/prisma-service/prisma/migrations/20240718102835_cloud_wallet_info_user_option/migration.sql, libs/prisma-service/prisma/schema.prisma
Implement an API for configuring a cloud-based wallet.
This feature enables admin to securely manage and store their wallets stored in the database
Create API for base wallet configure and manage in `cloud_wallet_user_info` table
=> feat: configure cloud base wallet

apps/user/src/user.service.ts
Implements decryption for the client ID and client secret.
To enhance security by ensuring sensitive information is encrypted clientId and client secret decrypt in verification functions.
Added utility functions to decrypt the client ID and client secret when they are needed.
Ensured the decryption process is secure and only occurs in controlled circumstances.
=> fix: client id and client secret decrypt

libs/common/src/common.utils.ts, libs/common/src/response-messages/index.ts
- Gracefully handle missing environment variable for deeplink domain url
- Currently with missing env variable, the exception results in unexpected errors
=> fix: gracefully handle missing deeplink domain url from env

apps/api-gateway/src/authz/jwt.strategy.ts
Implemented email validation for users with the "holder" role in jwt strategy file.
Ensures that only valid email addresses are used for check the email exists or not in token, improving data integrity and preventing potential errors related to incorrect email formats.
Added validation logic in the role guard to check the email format for users assigned the holder role.
=> fix: added user email validation for holder role guard

apps/api-gateway/src/connection/dtos/connection.dto.ts
-  Added outOfBandRecord and  reuseThreadId while collecting connection webhook
=> fix:collect reuse connection webhook events

apps/ledger/src/schema/schema.service.ts
- Allow platform schemas to be used for creating cred-def and issuing credentials
- Previously we restricted organizations other than the one that created the schema to use it
=> fix: unable to use platform archieved schema

apps/user/src/user.service.ts
- fix the dcryption clientId in the verification
- To check the clientId for redirect URL to verify the email
=> fix: solved the clientId dcryption in verification email

apps/api-gateway/src/issuance/dtos/issuance.dto.ts, apps/api-gateway/src/issuance/issuance.controller.ts, apps/issuance/interfaces/issuance.interfaces.ts, apps/issuance/src/issuance.service.ts, apps/verification/src/verification.service.ts, libs/common/src/cast.helper.ts, libs/common/src/interfaces/issuance.interface.ts
- Implemented reuseConnection functionality for OOB issuance using email
- Implemented reuseConnection functionality for bulk issuance
=> feat: reuse connection for issuance

apps/ledger/src/schema/repositories/schema.repository.ts, libs/prisma-service/prisma/seed.ts
- Fixes schema search due to default pageNumber
- Previously search text only allowed searching schema from 1st paginated page (by default). This caused issue for searching schema across all available schemas
=> fix: schema search during pagination

apps/api-gateway/src/authz/authz.controller.ts, apps/api-gateway/src/authz/dtos/forgot-password.dto.ts, apps/user/interfaces/user.interface.ts, apps/user/src/user.controller.ts, apps/user/src/user.service.ts, apps/user/templates/reset-password-template.ts
- Refactored forgot password API
- Refactored reset password email template
=> refactor: forgot password API

apps/agent-service/src/agent-service.service.ts, apps/ledger/src/credential-definition/credential-definition.service.ts, apps/ledger/src/credential-definition/repositories/credential-definition.repository.ts, apps/ledger/src/schema/repositories/schema.repository.ts, apps/ledger/src/schema/schema.controller.ts, apps/ledger/src/schema/schema.service.ts, apps/organization/repositories/organization.repository.ts, apps/organization/src/organization.service.ts, libs/prisma-service/prisma/migrations/20241114081928_added_is_schema_archived_flag_schema/migration.sql, libs/prisma-service/prisma/schema.prisma
- Implemented schema archiving functionality for deleted wallets.
=> feat: archive schema for deleted wallet

apps/ledger/src/credential-definition/credential-definition.service.ts, libs/common/src/interfaces/schema.interface.ts
- Added a check in the "Get All Credential Definitions by OrgId" API to fetch only those credential definitions whose aligned schemas are not archived.
=> refactor: get all cred defs by orgId functionality (#1084)

apps/api-gateway/common/exception-handler.ts, apps/api-gateway/src/main.ts, libs/common/src/response-messages/index.ts, libs/interceptors/nats.interceptor.ts
- Implemented NATS interceptor for NATS error message
- Not able to customize the NATS error messages
=> feat: global NATS interceptor implementation

.env.demo, apps/agent-provisioning/AFJ/scripts/start_agent.sh
- Some of the latest docker version requires `docker compose` instead of previously used `docker-compose`
- Change in scripts for local setup in the `.demo.env`. This configurations are only enabled for local setup using `pnpm` and not for `docker`ized builds
=> fix: local setup issues

apps/api-gateway/src/dtos/create-schema.dto.ts, apps/api-gateway/src/issuance/dtos/issuance.dto.ts, apps/api-gateway/src/issuance/issuance.controller.ts, apps/api-gateway/src/issuance/issuance.service.ts, apps/issuance/interfaces/issuance.interfaces.ts, apps/issuance/src/issuance.controller.ts, apps/issuance/src/issuance.repository.ts, apps/issuance/src/issuance.service.ts, libs/common/src/cast.helper.ts, libs/common/src/response-messages/index.ts
- Resolved below issues:
1). Indy organization was allowed to upload W3C schema csv for bulk issuance.
2). Indy organization was allowed to download W3C schema csv for bulk issuance.
3). Credential issuance succeeds with mismatched INDY orgId and W3C schema in bulk issue API.
4). Schema creation is successful, even if dataType is string, and if we provide properties for string dataType.
5). Unable to download csv template for INDY-based schemas in bulk issuance.
6). `isValidateSchema` conditions are not applicable for issuance using connection and issuance using email.
=> fix: issues related nested attributes in issuance process

apps/verification/src/verification.service.ts
Issue Fixed:
I addressed the error handling in the proof record retrieval endpoint where it was returning a 500 status code for non-existing records. The issue was in the verification service's error handling logic.
Changes Made:
1. Modified error handling in verification.service.ts for the getProofPresentationById method
2. Updated the error detection to properly identify "record not found" cases
3. Implemented proper 404 response using NestJS's NotFoundException
4. Maintained the original error message for clarity
Before:
- API returned 500 status code with a generic error
- Error structure was inconsistent with API standards
- Generic "Something went wrong!" message wasn't helpful
After:
- API now returns 404 status code for non-existing records
- Clear error message indicates the …
=> fix: Update GET proof record endpoint to return 404 for non-existing records

.github/workflows/scorecard.yml
- update upload-artifact-version to v4
- update artifact name in scorecard workflow
=> fix: update upload-artifact-version to v4 and artifact name in scorecard workflow

apps/agent-service/src/agent-service.service.ts, apps/ledger/src/schema/schema.service.ts, libs/common/src/common.constant.ts, libs/common/src/common.service.ts
- Added logic for `normalizedBaseUrl`
- Revert logic for `createSecp256k1KeyPair`
=> refactor: token API for tenant and create keypair

.env.demo, .env.sample, apps/agent-service/src/agent-service.service.ts
- Fixed all schema crash when no organization
=> Fix crash on all schema view when no organization exists
