credebl/platform

.env.sample
.gitignore
libs/prisma-service/prisma/data/credebl-master-table.json

- Worked on the refractoring of `.env.sample` file
- Worked on the `credebl-master-table.json` file for the DB seed feature

refractor: master table json file and .env sample

---

apps/organization/repositories/organization.repository.ts
apps/organization/src/organization.service.ts
apps/user/repositories/user.repository.ts

-  Implemented org and user to by default public
- Checked the same org name is exist in platform for update organization

refactor: implemented org and user to by default public

---

.env.sample
apps/agent-provisioning/AFJ/scripts/start_agent.sh
apps/agent-provisioning/AFJ/scripts/start_agent_ecs.sh
apps/api-gateway/src/connection/connection.controller.ts
apps/api-gateway/src/issuance/issuance.controller.ts
apps/api-gateway/src/verification/verification.controller.ts

I have made the following changes:
- Added and configured Indy-vdr.
- Integrated Askar.
- Upgraded AFJ to version 0.4.1.
- Indy-vdr has been added to enhance our project's capabilities related to decentralized identity.
- Askar integration improves our cryptographic security.
- Upgrading to AFJ 0.4.1 includes bug fixes and new features that enhance the overall performance and functionality of the project.
- Added Indy-vdr by including the necessary dependencies and configuring it according to the project's requirements.
- Integrated Askar by following the integration guidelines provided by the Askar documentation.
- Upgraded to AFJ 0.4.1 by updating the project's dependencies and making any necessary code changes to accommodate the new version.

feat: support afj-0.4.1

---

apps/api-gateway/src/ecosystem/dtos/get-all-sent-ecosystemInvitations-dto.ts
apps/api-gateway/src/ecosystem/ecosystem.controller.ts
apps/api-gateway/src/ecosystem/ecosystem.service.ts
apps/ecosystem/src/ecosystem.controller.ts
apps/ecosystem/src/ecosystem.repository.ts
apps/ecosystem/src/ecosystem.service.ts
libs/common/src/response-messages/index.ts

- Developed get Ecosystem invitations API (backend).
- It enables ecosystem members to view their Ecosystem invitations and manage them within the platform. 
- For better user experienece.

feat: get ecosystem invitations

---

apps/api-gateway/common/exception-handler.ts
apps/api-gateway/src/authz/authz.module.ts
apps/api-gateway/src/authz/decorators/roles.decorator.ts
apps/api-gateway/src/authz/guards/ecosystem-roles.guard.ts
apps/api-gateway/src/ecosystem/dtos/create-ecosystem-dto.ts
apps/api-gateway/src/ecosystem/ecosystem.controller.ts
apps/api-gateway/src/ecosystem/ecosystem.service.ts
apps/ecosystem/src/ecosystem.controller.ts
apps/ecosystem/src/ecosystem.repository.ts
apps/ecosystem/src/ecosystem.service.ts
libs/common/src/response-messages/index.ts
libs/enum/src/enum.ts

- Created ecosystem role guard
- Implemented ecosystem role guard on Ecosystem APIs
- To manage ecosystem APIs for various roles

feat: Ecosystem Role Guard

---

apps/api-gateway/src/ecosystem/dtos/accept-reject-ecosysteminvitation-dto.ts
apps/api-gateway/src/ecosystem/ecosystem.controller.ts
apps/api-gateway/src/ecosystem/ecosystem.service.ts
apps/ecosystem/dtos/accept-reject-ecosysteminvitation.dto.ts
apps/ecosystem/dtos/update-ecosystem-invitation.dto.ts
apps/ecosystem/dtos/update-ecosystemOrgs.dto.ts
apps/ecosystem/src/ecosystem.controller.ts
apps/ecosystem/src/ecosystem.repository.ts
apps/ecosystem/src/ecosystem.service.ts
libs/common/src/response-messages/index.ts

- Implemented accept or reject ecosystem invitations API.
- to respond ecosystem invitation

feat: accept or reject ecosystem invitations

---

apps/api-gateway/src/ecosystem/ecosystem.controller.ts

- Removed redundant function of endorser transaction list
- To display endorsement history and status of each transaction

fix: endorsor transaction list 

---

apps/ecosystem/src/ecosystem.repository.ts
apps/ecosystem/src/ecosystem.service.ts

- Refactored GET API for endorsement transactions with details of ecosystem lead.
- To display endorsement history and status of each transaction for all ecosystem.

fix: endorser list for ecosystem lead

---

apps/api-gateway/src/ecosystem/dtos/accept-reject-invitations.dto.ts
apps/api-gateway/src/ecosystem/dtos/create-ecosystem-dto.ts
apps/api-gateway/src/ecosystem/ecosystem.controller.ts
apps/ecosystem/dtos/accept-reject-ecosysteminvitation.dto.ts
apps/ecosystem/dtos/update-ecosystemOrgs.dto.ts
apps/ecosystem/src/ecosystem.repository.ts
apps/ecosystem/src/ecosystem.service.ts
libs/prisma-service/prisma/migrations/20231011095332_ecosystem_orgs_did/migration.sql
libs/prisma-service/prisma/schema.prisma

- Updated `ecosystem_orgs` model for `orgName` and `orgDid`
- Refactored references for this change in the APIs
- To get the ecosystem org details

refactor: ecosystem org model update

---

apps/api-gateway/src/ecosystem/ecosystem.controller.ts
apps/ecosystem/interfaces/ecosystem.interfaces.ts
apps/ecosystem/src/ecosystem.repository.ts
apps/ecosystem/src/ecosystem.service.ts
libs/common/src/response-messages/index.ts

- Implemented logic to store schema and credential-definition after submit transaction

feat: store schema and credential-definition after submitting transaction

---

apps/ecosystem/src/ecosystem.repository.ts

- Refactor the get ecosystem member list API
- Included ecosystem role information

refactor:included ecosystem role information

---

apps/ecosystem/enums/ecosystem.enum.ts
apps/ecosystem/src/ecosystem.repository.ts
apps/ecosystem/src/ecosystem.service.ts
apps/user/src/user.service.ts
libs/prisma-service/prisma/data/credebl-master-table.json
libs/prisma-service/prisma/migrations/20231012093420_ecosystem_config_key_value/migration.sql
libs/prisma-service/prisma/schema.prisma
libs/prisma-service/prisma/seed.ts

- Updated `ecosystem_orgs` model for `deploymentMode' parameter
- Refactored `ecosystem_config` to set all configurations with `key` and `value`.
- To configure the ecosystem configurations

refactor: ecosystem config settings

---

apps/ecosystem/src/ecosystem.repository.ts
apps/ecosystem/src/ecosystem.service.ts

- Removed `orgId` invalid validation for reject endorsement request

refactor: removed org validation for reject

---

apps/api-gateway/src/ecosystem/ecosystem.controller.ts
apps/ecosystem/interfaces/ecosystem.interfaces.ts
apps/ecosystem/src/ecosystem.repository.ts
apps/ecosystem/src/ecosystem.service.ts
libs/common/src/response-messages/index.ts

Added validation for the schema and credential definition (cred-def).
Changed the payload to include the value and type for the create request credential definition (cred-def).
The changes were made to enhance the security and accuracy of the credential creation process. By implementing schema and cred-def validation, we can ensure that the data being used is correct and secure.
Implemented schema and cred-def validation in the code.
Updated the payload structure to include "value" and "type" for create request credential definitions.

fix: Added validation for schema and cred-def and updated payload for create request cred-def

---

apps/ecosystem/src/ecosystem.controller.ts

fix: endorser request and submit

---

apps/api-gateway/src/ecosystem/ecosystem.controller.ts

fix: decline endorsement request

---

apps/api-gateway/src/ecosystem/ecosystem.controller.ts
apps/ecosystem/src/ecosystem.repository.ts
apps/ecosystem/src/ecosystem.service.ts

- Included ecosystem lead details in the ecosystem dashboard
- To display the ecosystem lead details to ecosystem members

refactor: ecosystem lead details included ecosystem dashboard

---

apps/api-gateway/src/ecosystem/dtos/request-schema.dto.ts
apps/ecosystem/interfaces/ecosystem.interfaces.ts
apps/ecosystem/src/ecosystem.controller.ts
apps/ecosystem/src/ecosystem.service.ts

- Implemented request body in credential-definition request

fix: implemented request body in credential definition request

---

apps/api-gateway/src/ecosystem/dtos/request-schema.dto.ts

- added attributes as an array of strings for request credential-definition

fix: added attributes as array of string

---

apps/ecosystem/src/ecosystem.service.ts

1. Solved the bug regarding the endorsement cred-def

fix: Solved the bug cred-def endorsement

---

apps/ecosystem/src/ecosystem.service.ts

- Fixed ecosystem invitation feature
- To send ecosystem invitation to join

fix: ecosystem invitations

---

apps/agent-service/src/agent-service.service.ts
apps/agent-service/src/main.ts
apps/api-gateway/src/organization/organization.controller.ts
apps/api-gateway/src/organization/organization.service.ts
apps/connection/src/connection.repository.ts
apps/connection/src/connection.service.ts
apps/organization/repositories/organization.repository.ts
apps/organization/src/organization.controller.ts
apps/organization/src/organization.service.ts
libs/common/src/response-messages/index.ts
libs/prisma-service/prisma/data/credebl-master-table.json

1. Support indicio demonet & mainnet network

feat: Support indicio demonet & mainnet

---

.env.sample
apps/agent-provisioning/AFJ/scripts/start_agent_ecs.sh
apps/agent-provisioning/src/agent-provisioning.service.ts
apps/agent-service/src/agent-service.service.ts

1. Modify the shell script for AFJ agent spin-up

fix: Modify the shell script for the spi-up the agent

---

apps/api-gateway/src/credential-definition/credential-definition.controller.ts
apps/api-gateway/src/credential-definition/credential-definition.service.ts
apps/api-gateway/src/helper-files/file-operation.helper.ts
apps/api-gateway/src/issuance/interfaces/index.ts
apps/api-gateway/src/issuance/issuance.controller.ts
apps/api-gateway/src/issuance/issuance.service.ts
apps/issuance/interfaces/issuance.interfaces.ts
apps/issuance/src/issuance.controller.ts
apps/issuance/src/issuance.repository.ts
apps/issuance/src/issuance.service.ts
apps/ledger/src/credential-definition/credential-definition.controller.ts
apps/ledger/src/credential-definition/credential-definition.service.ts
apps/ledger/src/credential-definition/interfaces/credential-definition.interface.ts
apps/ledger/src/credential-definition/repositories/credential-definition.repository.ts
libs/common/src/response-messages/index.ts
package-lock.json
package.json

- Implemented download CSV by credential definition.
- Implemented get all list of credential definitions mapped with schema.

feat: bulk-issuance APIs

---

.env.sample
libs/prisma-service/prisma/schema.prisma

- Updated schema prisma for db url of pooler
- To handle max connection limit issue

refactor: schema prisma for pooler

---

.env.sample
libs/prisma-service/prisma/schema.prisma

- Reverted the changes of database url pooler

refactor: revert schema prisma pooling

---

apps/api-gateway/src/authz/authz.controller.ts
apps/user/src/user.service.ts

- Refactor Sign in and sign up API's for password and passkey.

refactor: sign in sign up API

---

Dockerfiles/Dockerfile.issuance
apps/organization/repositories/organization.repository.ts
apps/organization/src/organization.service.ts

- Refactor public profile org GET API for credentials list
- To get org related credentials

refactor: public org profile for credentials

---

libs/prisma-service/prisma/migrations/20231018150349_endorsement_transaction_resource_id/migration.sql
libs/prisma-service/prisma/migrations/20231030133838_endorsement_transaction_resource_id/migration.sql
libs/prisma-service/prisma/schema.prisma

- Changed migration file for resourceId

fix changed migration for resource Id

---

apps/api-gateway/src/ecosystem/ecosystem.controller.ts

- Added orgId in params to get all ecosystem schemas

fix: orgId parameter for ecosystem schema

---

.gitignore

- Implemented uploaded folder on develop

feat: created uploadedFiles folder on develop

---

apps/ecosystem/src/ecosystem.repository.ts
apps/ecosystem/src/ecosystem.service.ts

fix:  ecosystem schema list issue

---

apps/ecosystem/src/ecosystem.repository.ts
apps/ecosystem/src/ecosystem.service.ts

- Fix endorse request for specific ecosystem.
- To endorse the request to ecosystem.

fix: endorse request for ecosystem

---

apps/connection/src/connection.repository.ts
apps/connection/src/connection.service.ts
apps/issuance/src/issuance.service.ts
apps/issuance/templates/out-of-band-issuance.template.ts
apps/verification/src/verification.service.ts
apps/verification/templates/out-of-band-verification.template.ts

This connection invitation related issues within the connection service.
The primary goal is to improve the handling of connection invitations, ensuring that a new invitation is not generated if one already exists. This will enhance the overall efficiency and reliability of the service.
Identified the issue related to connection invitations.
Implemented a check to prevent the generation of a new invitation when one already exists.
Conducted thorough testing to verify the effectiveness of the fix.

fix: refactor connection handling in the connection service

---

apps/api-gateway/src/ecosystem/dtos/create-ecosystem-dto.ts
apps/api-gateway/src/ecosystem/dtos/edit-ecosystem-dto.ts
apps/ecosystem/interfaces/ecosystem.interfaces.ts
apps/ecosystem/src/ecosystem.repository.ts
apps/ecosystem/src/ecosystem.service.ts
libs/prisma-service/prisma/migrations/20231101102151_auto_endorse_ecosystem_flag/migration.sql
libs/prisma-service/prisma/schema.prisma

- Implemented endorsement type settings for ecosystem lead
- To change the settings of endorsements for ecosystem lead

feat: auto-endorsement flag settings of ecosystem

---

apps/api-gateway/src/issuance/issuance.controller.ts
apps/issuance/src/issuance.service.ts

fix: added multer config

---

apps/api-gateway/src/issuance/issuance.controller.ts
apps/issuance/src/issuance.service.ts

- fixed the file rename issue (Testing on DEV)

fix: CSV upload issue on DEV instance

---

apps/api-gateway/src/main.ts
package-lock.json
package.json

- Security vulnerability  fixes
- Security vulnerabilities can lead to data breaches, exposing sensitive information
- Malicious actors actively seek out vulnerabilities to exploit
- Security breaches erode trust with  customers and users
- By using various security vulnerability mitigation techniques

Security vulnerability fixes

---

apps/api-gateway/src/issuance/issuance.controller.ts

- Added PWD path for file upload

fix: added PWD path for file upload

---

apps/api-gateway/src/issuance/issuance.controller.ts
apps/api-gateway/src/issuance/issuance.service.ts
apps/issuance/src/issuance.controller.ts
apps/issuance/src/issuance.service.ts

- API to test csv file using file path

fix : API to test csv file using file path

---

Dockerfiles/Dockerfile.api-gateway
Dockerfiles/Dockerfile.issuance

- Refactor issuance docker file for `uploadFiles` folder

refactor: uploadfiles changes in docker file

---

apps/api-gateway/src/ecosystem/ecosystem.controller.ts

- Displayed the ecosystem details to all thee roles of ecosystem.
- To view the ecosystem details for all roles of the organization.

refactor: rolewise ecosystem details access

---

apps/api-gateway/src/issuance/interfaces/index.ts
apps/api-gateway/src/issuance/issuance.controller.ts
apps/api-gateway/src/issuance/issuance.module.ts
apps/api-gateway/src/issuance/issuance.service.ts
apps/issuance/interfaces/issuance.interfaces.ts
apps/issuance/src/issuance.controller.ts
apps/issuance/src/issuance.module.ts
apps/issuance/src/issuance.service.ts
libs/aws/src/aws.module.ts
libs/aws/src/aws.service.spec.ts
libs/aws/src/aws.service.ts
libs/aws/src/index.ts
libs/aws/tsconfig.lib.json
libs/common/src/common.service.ts
nest-cli.json
package-lock.json
package.json
tsconfig.json

- Setup S3 bucket in libs
- Implemented file upload logic for bulk-issuance

feat: added S3 bucket for file upload

---

apps/api-gateway/src/main.ts
apps/issuance/src/issuance.service.ts
libs/aws/src/aws.service.ts
libs/common/src/response-messages/index.ts

fix: download CSV

---

apps/api-gateway/src/issuance/issuance.controller.ts

fix: file details API issue

---

apps/api-gateway/src/issuance/issuance.controller.ts
apps/issuance/src/issuance.service.ts

- Added logger for bulk-issuance

fix: added logger for bulk-issuance

---

apps/api-gateway/src/main.ts

- Configured helmet externally for X-Xss-Protection
- To enable Cross-Site Scripting (XSS) protection in web browsers

security-fix:Configured helmet for X-Xss-Protection

---

apps/api-gateway/src/user/dto/add-user.dto.ts

- Modified dto's class validator messages
- To fix a bug
- By modifying class validators messages

fix:modified dtos class validators messages

---

apps/issuance/src/issuance.processor.ts

- added return type for processor functions

fix: added return type for processor functions

---

apps/issuance/src/issuance.service.ts

- fixed multiple attribute issue

fix: multiple aattribute issue

---

apps/user/src/user.service.ts

- Added headless = new into pupeeteer launch

refactor: added puppeteer configuration

---

apps/issuance/src/issuance.service.ts

fix: changed socket emit logic

---

apps/issuance/src/issuance.service.ts

Describe the specific issue or task related to error handling in the bulk issuance process. Include any error messages, unexpected behaviors, or issues that need to be addressed.
Explain the importance or impact of resolving this issue. This could include potential problems it may cause, its relevance to the overall functionality, or how it affects users or other components of the system.
Provide details on the approach you plan to take to fix the error handling issue. This could involve changes to the code, updates to documentation, or any other necessary steps.

fix: error handling on the bulk issuance process

---

apps/api-gateway/src/issuance/issuance.controller.ts
apps/issuance/src/issuance.repository.ts
apps/issuance/src/issuance.service.ts
libs/common/src/response-messages/index.ts

-  Sorted file upload data descending with date time.
-  Fixed file name `blob issue`.
- To enhance the bulk issuance flow.

refactor: bulk issuance fixes

---

apps/api-gateway/src/user/user.controller.ts
apps/user/src/user.service.ts
apps/user/templates/arbiter-template.ts
apps/user/templates/participant-template.ts
apps/user/templates/winner-template.ts
apps/user/templates/world-record-template.ts
libs/aws/src/aws.service.ts
libs/common/src/interfaces/response.interface.ts
libs/enum/src/enum.ts

- Developed new certificate html templates
- Added label tag in controller
- Refactor user service code for sharing user template

refactor: developed new certificate html templates

---

apps/issuance/src/issuance.service.ts

- Added function for validating emails from uploaded file in bulk issuance API
- To restrict the user for uploading invalid email's

refact:added function for validating emails from uploaded file in bulk issuance API

---

apps/api-gateway/src/authz/socket.gateway.ts
apps/issuance/src/issuance.service.ts

-  Emitting error message  during the bulk issuance process failed  through socket
- To inform the end user that the bulk issuance process has encountered an error.

Error message emitted during the bulk issuance process failed through sockets

---

apps/issuance/src/issuance.module.ts
apps/user/src/user.service.ts

-  Refactor share credentials check for schema id.

refactor: share credentials API

---

apps/api-gateway/src/enum.ts
apps/issuance/src/issuance.repository.ts
apps/issuance/src/issuance.service.ts

- Added name as string
- Added `partially_completed` status

fix: file upload blob issue

---

apps/user/src/user.service.ts
apps/user/templates/arbiter-template.ts
apps/user/templates/participant-template.ts
apps/user/templates/winner-template.ts
apps/user/templates/world-record-template.ts
libs/aws/src/aws.service.ts

- Resolved puppeteer library issues.
- Uploaded certificate.svg file for more clarity of user certificates.
- Refactored puppeteer code.

refactor: Resolved puppeteer library issue

---

apps/api-gateway/src/authz/socket.gateway.ts
apps/issuance/src/issuance.service.ts

- Implemented separate socket for retry-bulk issuance

feat: added separate socket pattern for retry

---

apps/issuance/src/issuance.service.ts
apps/issuance/templates/out-of-band-issuance.template.ts

- Accept credential through deep linking

Accept credential through deep linking 

---

apps/user/templates/arbiter-template.ts
apps/user/templates/participant-template.ts
apps/user/templates/winner-template.ts
apps/user/templates/world-record-template.ts

- Developed user certificate templates.

refactor: user certificate templates

---

apps/api-gateway/src/issuance/issuance.controller.ts
apps/api-gateway/src/issuance/issuance.service.ts
apps/issuance/src/issuance.service.ts
libs/common/src/response-messages/index.ts
libs/prisma-service/prisma/migrations/20231123100506_id_to_uuid_data_type/migration.sql
libs/prisma-service/prisma/schema.prisma

1. Solved issues for the socket in bulk issuance
2. Added type uuid on the all tables

fix: solved socket emit for bulk-issuance

---

apps/api-gateway/src/connection/connection.controller.ts
apps/api-gateway/src/connection/connection.service.ts
apps/api-gateway/src/issuance/issuance.service.ts
apps/api-gateway/src/platform/platform.controller.ts
apps/api-gateway/src/platform/platform.service.ts
apps/connection/src/connection.repository.ts
apps/issuance/interfaces/issuance.interfaces.ts
apps/issuance/src/issuance.controller.ts
apps/issuance/src/issuance.repository.ts
apps/issuance/src/issuance.service.ts
apps/ledger/src/ledger.controller.ts
apps/ledger/src/ledger.service.ts
apps/ledger/src/repositories/ledger.repository.ts
libs/prisma-service/prisma/migrations/20231124163136_ledger_network_url/migration.sql
libs/prisma-service/prisma/schema.prisma

Introducing network URL fetch functionality on the ledger table.
To enable the ledger table to fetch data from external URLs, providing a more dynamic and versatile way of populating the ledger
Implemented a function that accepts a URL as a parameter, retrieves data from the URL, and updates the ledger table with the fetched data.

feat: network url fetch on the ledger table

---

apps/user/templates/arbiter-template.ts
apps/user/templates/participant-template.ts
apps/user/templates/winner-template.ts
apps/user/templates/world-record-template.ts

-  Refactor all the certificate templates

refactor: certificate templates

---

apps/issuance/templates/out-of-band-issuance.template.ts

-  Refactor out of band email template

refactor: out of band email template

---

apps/issuance/templates/out-of-band-issuance.template.ts

-  Changed logo url in oob template

refactor: Oob template

---

apps/issuance/templates/out-of-band-issuance.template.ts

-  Refactor oob template for credebl logo

refactor:oob mail template

---

libs/prisma-service/prisma/migrations/20231127132350_map_ecosystem_orgs/migration.sql

- Refactored migration file of ecosystem org mapping for orgId column.

refactor: map ecosystem organization

---

apps/user/templates/arbiter-template.ts
apps/user/templates/participant-template.ts
apps/user/templates/winner-template.ts
apps/user/templates/world-record-template.ts

- Refactor certificate templates content

refactor: Certificate templates content

---

apps/ecosystem/src/ecosystem.repository.ts
apps/organization/repositories/organization.repository.ts
libs/user-activity/repositories/index.ts

API Response Refactoring for the following APIs:
- Get all Organizations
- Get Organization Invitations
- Get Ecosystem Invitations
- Get User's Recent Activity

refactor:Api response

---

apps/api-gateway/src/ecosystem/dtos/request-schema.dto.ts
apps/api-gateway/src/ecosystem/ecosystem.controller.ts
apps/ecosystem/src/ecosystem.service.ts
libs/common/src/response-messages/index.ts

-  Included validations for the payload of endorsement requests.

fix: Validations in endorsement requests.

---

apps/api-gateway/src/dtos/create-schema.dto.ts
apps/api-gateway/src/ecosystem/dtos/create-ecosystem-dto.ts
apps/api-gateway/src/issuance/dtos/issuance.dto.ts
apps/ledger/src/schema/schema.service.ts

fix: Applied trim validations 

---

apps/api-gateway/src/ecosystem/dtos/edit-ecosystem-dto.ts
apps/api-gateway/src/ecosystem/ecosystem.controller.ts
apps/ecosystem/interfaces/ecosystem.interfaces.ts
apps/ecosystem/src/ecosystem.repository.ts
apps/ecosystem/src/ecosystem.service.ts
apps/ledger/src/interfaces/ledgers.interface.ts
apps/ledger/src/ledger.controller.ts
apps/ledger/src/ledger.service.ts
apps/ledger/src/repositories/ledger.repository.ts
libs/common/src/response-messages/index.ts
libs/prisma-service/prisma/migrations/20231211112032_ecosystem_ledgers_column/migration.sql
libs/prisma-service/prisma/schema.prisma

- Include `ledgers` column in the ecosystem model
- Store ledger details while  create ecosystem.
- Match org ledger network with ecosystem while accept ecosystem invitation.
- Check if the `ledger` details present in `ecosystem` while sending invitation to join
- Refactor edit ecosystem for ledger details

refactor: ecosystem ledger mapping

---

apps/ecosystem/src/ecosystem.service.ts

- Refactored `reject` ecosystem invitation feature

refactor: ecosystem ledger restrictions

---

apps/ecosystem/interfaces/ecosystem.interfaces.ts
apps/ecosystem/src/ecosystem.service.ts
apps/verification/src/repositories/verification.repository.ts

- Added request Id in payload.
- Resolved edit ecosystem logo issue.

fix: request id issue

---

apps/api-gateway/src/interfaces/ISchemaSearch.interface.ts
apps/api-gateway/src/platform/platform.controller.ts
apps/api-gateway/src/platform/platform.service.ts
apps/api-gateway/src/schema/dtos/get-all-schema.dto.ts
apps/api-gateway/src/schema/schema.controller.ts
apps/api-gateway/src/schema/schema.service.ts
apps/ledger/src/schema/enum/schema.enum.ts
apps/ledger/src/schema/interfaces/schema-payload.interface.ts
apps/ledger/src/schema/interfaces/schema.interface.ts
apps/ledger/src/schema/repositories/schema.repository.ts
apps/ledger/src/schema/schema.controller.ts
apps/ledger/src/schema/schema.service.ts
libs/common/src/interfaces/schema.interface.ts
libs/common/src/response-messages/index.ts

- Refactored the GET API for `/orgs/{orgId}/schemas`.
- Handled all the validations and negative scenarios.

refactor: Schemas By Organization

---

apps/api-gateway/src/connection/connection.controller.ts
apps/api-gateway/src/connection/connection.service.ts
apps/api-gateway/src/connection/dtos/get-all-connections.dto.ts
apps/api-gateway/src/interfaces/IConnectionSearch.interface.ts
apps/api-gateway/src/interfaces/ISchemaSearch.interface.ts
apps/connection/src/connection.controller.ts
apps/connection/src/connection.repository.ts
apps/connection/src/connection.service.ts
apps/connection/src/enum/connection.enum.ts
apps/connection/src/interfaces/connection.interfaces.ts
libs/common/src/interfaces/connection.interface.ts
libs/common/src/interfaces/response.interface.ts
libs/common/src/response-messages/index.ts

- Refactored the GET API ```orgs/{orgId}/connections```
1. Implemented a well-defined interface by replacing previous existing ```Promise<object>```.
2. Ensured consistency of API status codes.
3. Modified the NATS function.
4. Tested with both positive and negative scenarios.
-  The implementation of a well-defined interface enhances code readability and makes the structure of the API response more explicit.
-  Ensuring consistent API status codes improves communication between different components of the system and enhances overall reliability.
-  Replaced the return type with a well-defined interface to enhance code clarity.
-  Checked and standardized API status codes to ensure a uniform response.
- Modified the NATS function to accommodate the adjustments made in the API.

refactor: Connections by Organization

---

apps/api-gateway/src/authz/guards/org-roles.guard.ts
apps/api-gateway/src/schema/dtos/get-all-schema.dto.ts
apps/api-gateway/src/schema/schema.controller.ts
apps/api-gateway/src/schema/schema.service.ts
apps/ledger/src/schema/enum/schema.enum.ts
apps/ledger/src/schema/interfaces/schema-payload.interface.ts
apps/ledger/src/schema/repositories/schema.repository.ts
apps/ledger/src/schema/schema.controller.ts
apps/ledger/src/schema/schema.service.ts
libs/common/src/interfaces/response.interface.ts
libs/common/src/interfaces/schema.interface.ts
libs/common/src/response-messages/index.ts

- Refactored the GET API for `/orgs/{orgId}/schemas/{schemaId}/cred-defs`.
- Handled all the validations and negative scenarios.

Credential definition by schema Id

---

apps/agent-service/src/agent-service.controller.ts
apps/agent-service/src/agent-service.service.ts
apps/agent-service/src/interface/agent-service.interface.ts
apps/agent-service/src/repositories/agent-service.repository.ts
apps/api-gateway/src/agent-service/agent-service.controller.ts
apps/api-gateway/src/agent-service/agent-service.service.ts
apps/api-gateway/src/agent-service/interface/agent-service.interface.ts
libs/common/src/common.constant.ts

The proposed changes focus on refining the API agent health.
To improve the overall performance and reliability of the API agent, ensuring its robust health and functionality.
Review and analyze the current state of the API agent.
Implement necessary code changes to enhance the API agent's health.
Thoroughly test the modifications to ensure they meet quality standards.

refactor: API agent health

---

apps/api-gateway/src/issuance/dtos/get-all-issued-credentials.dto.ts
apps/api-gateway/src/issuance/interfaces/index.ts
apps/api-gateway/src/issuance/issuance.controller.ts
apps/api-gateway/src/issuance/issuance.service.ts
apps/issuance/enum/issuance.enum.ts
apps/issuance/interfaces/issuance.interfaces.ts
apps/issuance/src/issuance.controller.ts
apps/issuance/src/issuance.repository.ts
apps/issuance/src/issuance.service.ts
libs/common/src/interfaces/issuance.interface.ts

- Refactored the GET API ```/orgs/:orgId/credentials```
1. Implemented a well-defined interface by replacing the previous existing ```Promise<object>```.
2. Checked validations on payload.
3. Refactor response
4. Ensured consistency of API status codes.
5. Modified the NATS function.
-  The implementation of a well-defined interface enhances code readability and makes the structure of the API response more explicit.
-  Ensuring consistent API status codes improves communication between different components of the system and enhances overall reliability.
- Replaced the return type with a well-defined interface to enhance code clarity.
- Modified the NATS function to accommodate the adjustments made in the API.

refactor: issued credential list API

---

apps/agent-provisioning/AFJ/scripts/start_agent_ecs.sh

Changing the path for the port file.
Change the path for the port file on shell script and improve overall maintainability.
By making necessary code modifications and updating relevant documentation

Changes the path for the port-file

---

apps/api-gateway/src/user/dto/add-user.dto.ts
apps/api-gateway/src/user/user.controller.ts
apps/api-gateway/src/user/user.service.ts
apps/user/src/user.controller.ts
apps/user/src/user.service.ts
libs/common/src/response-messages/index.ts

- Refactored following APIs:
1. PUT `/users` Update user profile
2. PUT `/users/password/{email}` Store user password details
1. Ensured consistency of API status codes.
4. Modified the NATS function.
5. Tested with both positive and negative scenarios.
1. Checked and standardized API status codes to ensure a uniform response.
2. Modified the NATS function to accommodate the adjustments made in the API.
1. Ensuring consistent API status codes improves communication between different components of the system and enhances overall reliability.

refacto: User profile and password api

---

apps/api-gateway/src/authz/jwt.strategy.ts
apps/api-gateway/src/user/user.controller.ts
apps/api-gateway/src/user/user.service.ts

- Fixed issue: Unable to get user details from GET User API in User's module.

fix:get user details api

---

apps/organization/repositories/organization.repository.ts

- Make Organization profile by default private.

make org profile private

---

apps/api-gateway/src/user/user.controller.ts
apps/organization/repositories/organization.repository.ts
apps/organization/src/organization.service.ts
apps/user/src/user.controller.ts
apps/user/src/user.service.ts
libs/common/src/response-messages/index.ts

- Make org profile private by default organization create
- Accept reject invitation API
- Accept reject invitation API

merge: nats-refactor to develop

---

apps/ecosystem/src/ecosystem.service.ts

1. Resolved the issue related to the "apiKey not found" error when attempting to sign and submit an endorsement.
1. The problem was occurring due to the absence of the apiKey during the process of signing and submitting an endorsement. This was preventing successful completion of the operation.
1. Identified the root cause of the issue, which was the missing apiKey during the sign and submit endorsement process.
2. Implemented a fix to ensure that the apiKey is properly included and accessible during the operation.
3. Tested the solution to confirm that the "apiKey not found" issue is resolved.

fix: solved the bug for sign and submit endorsement 

---

apps/api-gateway/src/organization/organization.controller.ts
apps/api-gateway/src/organization/organization.service.ts
apps/organization/interfaces/organization.interface.ts
apps/organization/repositories/organization.repository.ts
apps/organization/src/organization.controller.ts
apps/organization/src/organization.service.ts
libs/common/src/response-messages/index.ts

Refactored following APIs from organization module:
- GET `/orgs/profile/{orgId}` Organization Profile.
- GET `/orgs/public-profile` Get all public profile of organizations.
- GET `/orgs/roles` Fetch org-roles details.
- Ensured consistency of API status codes.
- Modified the NATS function.
- Tested with both positive and negative scenarios.
- Ensuring consistent API status codes improves communication between different components of the system and enhances overall reliability.

refactor: organization profile APIs

---

apps/api-gateway/src/organization/dtos/create-organization-dto.ts
apps/api-gateway/src/organization/dtos/send-invitation.dto.ts
apps/api-gateway/src/organization/dtos/update-user-roles.dto.ts
apps/api-gateway/src/organization/organization.controller.ts
apps/api-gateway/src/organization/organization.service.ts
apps/organization/interfaces/organization.interface.ts
apps/organization/repositories/organization.repository.ts
apps/organization/src/organization.controller.ts
apps/organization/src/organization.service.ts
libs/common/src/interfaces/organizations.interface.ts
libs/common/src/response-messages/index.ts

Refactored following APIs from organization module:
1. Get all invitations
2. Get all organizations', 
3. Get organization user list 
4. Create a new organization'
5. Update user roles
6. Update organization
7. Delete organziation
- Ensured consistency of API status codes.
- Modified the NATS function.
- Tested with both positive and negative scenarios.
- Ensuring consistent API status codes improves communication between different components of the system and enhances overall reliability.

refactor: org invitations APIs

---

apps/ecosystem/interfaces/ecosystem.interfaces.ts
apps/ecosystem/src/ecosystem.repository.ts
apps/organization/interfaces/organization.interface.ts
apps/organization/repositories/organization.repository.ts

-  Added total items in the get-all ecosystem API
-  Added total items in the get-all organization API
- To improve pagination logic

fix : pagination enhancement

---

apps/api-gateway/src/agent-service/dto/register-webhook-dto.ts
apps/api-gateway/src/app.module.ts
apps/api-gateway/src/connection/connection.controller.ts
apps/api-gateway/src/connection/connection.service.ts
apps/api-gateway/src/issuance/issuance.controller.ts
apps/api-gateway/src/issuance/issuance.service.ts
apps/api-gateway/src/main.ts
apps/api-gateway/src/verification/verification.controller.ts
apps/api-gateway/src/verification/verification.service.ts
apps/api-gateway/src/webhook/dtos/register-webhook-dto.ts
apps/api-gateway/src/webhook/dtos/webhook-response-dto.ts
apps/api-gateway/src/webhook/webhook.controller.ts
apps/api-gateway/src/webhook/webhook.module.ts
apps/api-gateway/src/webhook/webhook.service.ts
apps/webhook/interfaces/webhook.interfaces.ts
apps/webhook/src/main.ts
apps/webhook/src/webhook.controller.ts
apps/webhook/src/webhook.module.ts
apps/webhook/src/webhook.repository.ts
apps/webhook/src/webhook.service.ts
apps/webhook/tsconfig.app.json
libs/common/src/response-messages/index.ts
libs/prisma-service/prisma/migrations/20240105143603_register_webhook_url/migration.sql
libs/prisma-service/prisma/schema.prisma
nest-cli.json

- Register organization specific webhook.
- Dispatch organization-specific connection issuance and verification webhook data to the registered URL

feat: Register organization specific webhook and Dispatch organization-specific webhook data to the registered URL

---

apps/api-gateway/src/ecosystem/dtos/get-members.dto.ts
apps/api-gateway/src/ecosystem/ecosystem.service.ts
apps/ecosystem/interfaces/ecosystemMembers.interface.ts
apps/ecosystem/src/ecosystem.repository.ts
apps/ecosystem/src/ecosystem.service.ts
apps/issuance/src/issuance.repository.ts
apps/ledger/src/credential-definition/repositories/credential-definition.repository.ts
apps/ledger/src/schema/repositories/schema.repository.ts
libs/enum/src/enum.ts

- Implemented pagination with sorting, and searching in ecosystem members get API
- Improved sorting enum

feat: member list pagination

---

apps/agent-provisioning/AFJ/scripts/start_agent.sh

- Changes on start agent shell script for get token

refactor: added the changes for get the AFJ token

---

apps/issuance/src/issuance.service.ts

fix: pagination issue

---

apps/api-gateway/src/organization/dtos/send-invitation.dto.ts
apps/api-gateway/src/organization/organization.controller.ts
apps/organization/src/organization.service.ts

- Refactored create Organization API response.

fix: Create Organization POST API response

---

apps/api-gateway/src/verification/verification.controller.ts

- Refactored proof verification API for response

refactor: proof verification API

---

apps/api-gateway/src/ecosystem/ecosystem.controller.ts
apps/api-gateway/src/ecosystem/ecosystem.service.ts
apps/ecosystem/interfaces/ecosystem.interfaces.ts
apps/ecosystem/src/ecosystem.controller.ts
apps/ecosystem/src/ecosystem.repository.ts
apps/ecosystem/src/ecosystem.service.ts
libs/common/src/response-messages/index.ts

- Refactored create ecosystem API response.
- Returning data with IDs in API responses facilitates efficient client-side updates and referencing.

refactor: Ecosystem API response

---

apps/ledger/src/schema/schema.service.ts

- Refactored POST API for create schema

fix: create schema api response

---

apps/api-gateway/src/ecosystem/ecosystem.controller.ts
apps/ecosystem/src/ecosystem.repository.ts

- Refactored delete ecosystem invitation API response.

fix: Delete ecosystem invitations API

---

apps/api-gateway/src/ecosystem/ecosystem.controller.ts
apps/api-gateway/src/ecosystem/ecosystem.service.ts
apps/ecosystem/src/ecosystem.controller.ts
apps/ecosystem/src/ecosystem.repository.ts
apps/ecosystem/src/ecosystem.service.ts

Refactored Ecosystem APIs responses

refactor: Ecosystem APIs responses

---

apps/api-gateway/src/ecosystem/ecosystem.controller.ts
apps/ecosystem/src/ecosystem.service.ts
libs/common/src/response-messages/index.ts

- Changes in Endorsement success messages.

refactor: endorsement success messages.

---

libs/prisma-service/prisma/migrations/20240206071023_inbound_ip_platform_config/migration.sql
libs/prisma-service/prisma/schema.prisma

1. Added the migration file for inbound IP

Added the migration for the inbound Ip

---

Dockerfiles/Dockerfile.webhook

created webhook docker file

---

Dockerfiles/Dockerfile.webhook

- Changes from dev to qa branch

changes from dev to qa branch

---

apps/ecosystem/src/ecosystem.service.ts

- Fixed issue platform not allowing endorsement request with the same schema and version

fix: platform not allowing endorsement request with the same schema and version

---

apps/user/src/user.service.ts

-  fixes of user registration for keycloak

fix: user registration for keycloak

---

apps/ecosystem/src/ecosystem.service.ts

- Fixed issue not able to create cred-def after initially rejecting it.

fix:not able to create cred-def after initially rejecting.

---

apps/connection/src/connection.service.ts

fix: added logger

---

apps/ecosystem/src/ecosystem.service.ts

Resolved the endorsement credDef decline and approved transaction request issue.
To address a bug causing endorsement credDef decline and to ensure proper approval of transaction requests.
Implemented changes to fix the endorsement credDef decline and approve transaction request issue.

fix: solved the edorsement credDef decline issue

---

apps/api-gateway/src/verification/dto/webhook-proof.dto.ts

1. Included the format data within the proof's webhook

feat: Included the format data within the proof's webhook

---

apps/api-gateway/src/app.module.ts
apps/api-gateway/src/notification/dtos/notification.dto.ts
apps/api-gateway/src/notification/interfaces/notification.interfaces.ts
apps/api-gateway/src/notification/notification.controller.ts
apps/api-gateway/src/notification/notification.module.ts
apps/api-gateway/src/notification/notification.service.ts
apps/api-gateway/src/organization/dtos/create-organization-dto.ts
apps/notification/interfaces/notification.interfaces.ts
apps/notification/src/main.ts
apps/notification/src/notification.controller.ts
apps/notification/src/notification.module.ts
apps/notification/src/notification.repository.ts
apps/notification/src/notification.service.ts
apps/notification/tsconfig.app.json
apps/organization/dtos/create-organization.dto.ts
apps/organization/src/organization.service.ts
libs/common/src/response-messages/index.ts
libs/prisma-service/prisma/migrations/20240219142237_notification/migration.sql
libs/prisma-service/prisma/schema.prisma
nest-cli.json

- Added a push notification module to enable real-time updates.
- Created a push notification microservice for handling notification logic.
- Improved user engagement by providing timely updates and notifications.
- Separated notification functionality into a microservice for scalability and maintainability.
- Added API endpoint for registering organization webhooks.
- Implemented API for storing FCM tokens, user keys, and organization IDs.
- Ensured proper validation and security measures in API endpoints.

feat: implement push notification module and microservice

---

apps/connection/src/connection.service.ts
apps/issuance/src/issuance.repository.ts
apps/organization/interfaces/organization.interface.ts
apps/organization/repositories/organization.repository.ts
apps/organization/src/organization.service.ts

- Modify the create invitation function, So that it checks if the Organization logo and Organization name have been updated, then a new connection invitation will be created.
- This modification ensures that invitations accurately reflect the current changes of the organization. If the organization's logo or name changes, it's essential that invitations reflect these updates.

feat: Create new connection invitation

---

apps/api-gateway/src/issuance/dtos/issuance.dto.ts
apps/issuance/src/issuance.service.ts

- Fixed issue regarding issuance API with old schema details.

fix: issuance API with required attribute

---

apps/user/src/user.service.ts

- Added restriction of user registration if already registered on `keycloak` either on `supabase`

fix: user registration restrictions

---

Dockerfiles/Dockerfile.user

- fixed download puppeteer issue in docker.user file

fixed Puppeteer issue

---

apps/agent-provisioning/AFJ/scripts/start_agent.sh
apps/agent-service/src/agent-service.controller.ts
apps/agent-service/src/agent-service.service.ts
apps/agent-service/src/interface/agent-service.interface.ts
apps/api-gateway/src/connection/connection.controller.ts
apps/api-gateway/src/connection/connection.service.ts
apps/api-gateway/src/connection/dtos/question-answer.dto.ts
apps/connection/src/connection.controller.ts
apps/connection/src/connection.service.ts
apps/connection/src/interfaces/question-answer.interfaces.ts
libs/common/src/common.constant.ts
libs/common/src/response-messages/index.ts

- Added send question API
- Added get all question answer record API
- Added webhook for question answer

feat: add question answer protocol 

---

apps/ecosystem/src/ecosystem.service.ts
apps/ledger/src/schema/interfaces/schema-payload.interface.ts
apps/ledger/src/schema/repositories/schema.repository.ts
apps/ledger/src/schema/schema.controller.ts
apps/ledger/src/schema/schema.service.ts

- Enhancing Endorsement Schema Validation

fix: check the schema if exist or not in endorsement

---

apps/ecosystem/src/ecosystem.service.ts
apps/ledger/src/schema/repositories/schema.repository.ts
apps/ledger/src/schema/schema.controller.ts
apps/ledger/src/schema/schema.service.ts

Enhancements to Schema Exist Query Handling

fix: solved issues for the schema exist query on the ecosystem

---

apps/issuance/interfaces/issuance.interfaces.ts
apps/issuance/src/issuance.service.ts

- Removed extra attribute from issuance payload.

fix: extra attribute in issuance payload

---

apps/verification/src/verification.service.ts

Resolved verification predicates values to ensure accurate validation.
The verification predicates were causing inconsistencies, and this fix ensures the correctness of validation processes.
Updated the relevant code to address and resolve the verification predicates values.
Made changes to ensure accurate validation during the verification process.

fix: solved verification predicates values

---

libs/client-registration/src/client-registration.service.ts
libs/common/src/common.service.ts

- Refactored the common service and logs
- Refactored the client service and logs

refactor: common service & client service

---

Dockerfiles/Dockerfile.notification
apps/notification/src/main.ts
apps/notification/src/notification.module.ts

Added Dockerfile for the Notification Service
To enhance containerization and deployment capabilities, providing a standardized environment for the Notification Service.
Introduced a Dockerfile configuration for the Notification Service to enable easy containerization and deployment.

added the dockerfile for notification service

---

apps/api-gateway/src/issuance/dtos/issuance.dto.ts
apps/api-gateway/src/issuance/interfaces/index.ts
apps/api-gateway/src/issuance/issuance.controller.ts
apps/api-gateway/src/issuance/issuance.service.ts
apps/api-gateway/src/issuance/utils/helper.ts
apps/issuance/interfaces/issuance.interfaces.ts
apps/issuance/src/issuance.controller.ts
apps/issuance/src/issuance.service.ts
libs/common/src/response-messages/index.ts

- Added jsonld and indy credential type 
- Added W3C credential issuance - create offer oob

feat: add W3C credential issuance 

---

apps/api-gateway/src/agent-service/dto/create-tenant.dto.ts

- Applied validations for ledger id.

fix: ledger id validations

---

apps/user/src/user.service.ts

- Fixed the forgot password flow for old `supabase` users.

fix: forgot password supauser

---

apps/api-gateway/src/issuance/dtos/issuance.dto.ts
apps/api-gateway/src/issuance/interfaces/index.ts
apps/api-gateway/src/issuance/issuance.controller.ts
apps/api-gateway/src/issuance/issuance.service.ts
apps/api-gateway/src/issuance/utils/helper.ts
apps/api-gateway/src/verification/dto/request-proof.dto.ts
apps/api-gateway/src/verification/enum/verification.enum.ts
apps/api-gateway/src/verification/verification.controller.ts
apps/issuance/interfaces/issuance.interfaces.ts
apps/issuance/src/issuance.service.ts
apps/verification/src/interfaces/verification.interface.ts
apps/verification/src/verification.service.ts
libs/common/src/response-messages/index.ts

- Refactor the bulk issuance and with email issuance functionality
- Error handling to the bulk issuance in OOB issuance functionality
- Refactor success message response

develop to qa

---

apps/verification/src/verification.service.ts

- Resolved imageurl condition for oob-verification

fix imageurl field bug

---

.env.sample
apps/ecosystem/src/ecosystem.repository.ts
apps/ecosystem/src/ecosystem.service.ts
apps/issuance/src/issuance.service.ts
libs/client-registration/src/client-registration.service.ts

Resolved the endorsement credential definition.
Added the keycloak configuration in .env.sample file.
When submit the credential definition getting error schema name not found.
Added the validation if getting the type as a schema on the endorsement.

fix: solved the endosement credential definition

---

apps/issuance/src/issuance.service.ts

**What**?
Remove Unnecessary logs from being logged.
**Where?**
In Issuance service

fix: remove unnecessary logs

---

.env.sample

- Changes in `.env.sample` file for white labelling changes on Platform.

feat: make credebl white label backend

---

apps/api-gateway/src/authz/guards/org-roles.guard.ts
apps/api-gateway/src/organization/organization.controller.ts

- Refactor `orgRoleGuard` to manage the resource access condition
- Applied `UserAccessGuard` to the create organization and get all organizations.

refactor: org role guard

---

libs/client-registration/src/client-registration.service.ts

- Refactored the client scopes for getting the client credentials

refactor: client scopes

---

apps/issuance/src/issuance.service.ts

- Changed exception format for empty csv file.

fix: exception handling for csv file

---

apps/agent-service/src/agent-service.controller.ts
apps/agent-service/src/agent-service.service.ts
apps/agent-service/src/interface/agent-service.interface.ts
apps/agent-service/src/repositories/agent-service.repository.ts
apps/api-gateway/src/agent-service/agent-service.controller.ts
apps/api-gateway/src/agent-service/agent-service.service.ts
apps/api-gateway/src/agent-service/dto/create-did.dto.ts
apps/api-gateway/src/agent-service/dto/create-wallet.dto.ts
apps/api-gateway/src/agent-service/interface/agent-service.interface.ts
libs/common/src/cast.helper.ts
libs/common/src/common.constant.ts
libs/common/src/did.validator.ts
libs/common/src/interfaces/did.interface.ts
libs/common/src/response-messages/index.ts
libs/enum/src/enum.ts
libs/prisma-service/prisma/data/credebl-master-table.json
libs/prisma-service/prisma/migrations/20240223140032_ledger_config/migration.sql
libs/prisma-service/prisma/schema.prisma
libs/prisma-service/prisma/seed.ts

- Implementation of multiple DID methods support during wallet creation
- Segregation of create wallet and create DID functionality.
- A single endpoint ensures the generality of DID creation.

feat: support multiple did methods

---

libs/common/src/common.service.ts

Added the logs and env config on the common service

Added the logs and env config on the common service

---

apps/verification/src/verification.service.ts
libs/common/src/common.service.ts

Fixed the issue related to out-of-band (OOB) verification with email.
To ensure that users can successfully verify their email addresses without encountering errors or issues.
Identified the root cause of the problem related to OOB verification with email.
Implemented necessary code changes to resolve the issue.

fix: solved issue for oob verification with email

---

apps/agent-service/src/agent-service.service.ts

The task involves updating the web DID document in the database.
Updating the web DID document in the database ensures that the information stored accurately reflects the current state of the decentralized identity associated with the web application
Created DID document to reflect to store in the database

fix: web didDoc updation in database

---

apps/issuance/templates/out-of-band-issuance.template.ts
apps/verification/templates/out-of-band-verification.template.ts

- Changes for app store links and play store links for ADEYA.

feat: white labelling changes for ADEYA links

---

apps/api-gateway/src/agent-service/dto/create-did.dto.ts
libs/common/src/did.validator.ts

- Applied private key validations

fix: private key length validations

---

apps/verification/src/verification.service.ts
apps/verification/templates/out-of-band-verification.template.ts

Fixes email template button linking issue for OOB verification

fix: email template for oob verification

---

apps/api-gateway/src/authz/guards/org-roles.guard.ts

fix: incorrect error message

---

apps/ledger/src/credential-definition/credential-definition.service.ts

Fixes get API Key not found error while getting cred-def by id 
Fixes API Key error while getting credential definition by id

fix: API error for get credef by id

---

apps/api-gateway/src/fido/fido.service.ts
apps/user/repositories/fido-user.repository.ts
apps/user/src/fido/dtos/fido-user.dto.ts
apps/user/src/fido/fido.controller.ts

- updated webauthn version to the latest (9.0.3)
- ISO 17 and above were not working

refactor: updated webauthn version to latest (9.0.3)

---

apps/api-gateway/src/main.ts

Allowed `DELETE` method to perform.

fix: HTTP method

---

apps/utility/src/utilities.service.ts

hotfix: add shorten url

---

apps/api-gateway/src/user/dto/share-certificate.dto.ts
apps/user/interfaces/user.interface.ts
apps/user/src/user.service.ts
apps/user/templates/event-certificates.ts
apps/user/templates/event-pinnacle.ts
libs/aws/src/aws.service.ts
libs/enum/src/enum.ts

- Added option to share event certificates
- Added `template` for pinnacle and other certificates
- Added Qr-code generation logic

hotfix: event certificate share option

---

Dockerfiles/Dockerfile.agent-provisioning
Dockerfiles/Dockerfile.agent-service
Dockerfiles/Dockerfile.api-gateway
Dockerfiles/Dockerfile.connection
Dockerfiles/Dockerfile.ecosystem
Dockerfiles/Dockerfile.issuance
Dockerfiles/Dockerfile.ledger
Dockerfiles/Dockerfile.notification
Dockerfiles/Dockerfile.organization
Dockerfiles/Dockerfile.user
Dockerfiles/Dockerfile.utility
Dockerfiles/Dockerfile.verification
Dockerfiles/Dockerfile.webhook

Docker file changes
- Removed unnecessary comments.
- Removed root path from agent-provisioning docker file.

Dockerfile changes

---

apps/api-gateway/src/issuance/dtos/issuance.dto.ts

- Add outOfBandId into issuance webhook
- Identify common Id's within all webhook messages.

refactor:added `outOfBandId` into issuance webhook

---

apps/api-gateway/src/connection/dtos/connection.dto.ts
apps/api-gateway/src/dtos/create-schema.dto.ts
apps/api-gateway/src/ecosystem/dtos/create-ecosystem-dto.ts
apps/api-gateway/src/ecosystem/dtos/edit-ecosystem-dto.ts
apps/api-gateway/src/main.ts
apps/api-gateway/src/organization/dtos/create-organization-dto.ts
apps/api-gateway/src/organization/dtos/update-organization-dto.ts
apps/api-gateway/src/organization/organization.controller.ts
apps/api-gateway/src/verification/dto/get-all-proof-requests.dto.ts
apps/api-gateway/src/verification/dto/request-proof.dto.ts
apps/api-gateway/src/verification/interfaces/verification.interface.ts
apps/api-gateway/src/verification/verification.controller.ts
apps/verification/src/interfaces/verification.interface.ts
apps/verification/src/repositories/verification.repository.ts
libs/common/src/cast.helper.ts
libs/common/src/dtos/pagination.dto.ts

- Added validation regarding security related issues in the api-gateway and verification service

fix: hotfix for security issues

---

apps/utility/src/utilities.service.ts

- Adds hotfixes that were made to main, to develop

fix: add hotfixes from main

---

Dockerfiles/Dockerfile.utility

added openssl installation

---

apps/api-gateway/src/issuance/dtos/issuance.dto.ts
apps/api-gateway/src/issuance/dtos/multi-connection.dto.ts
apps/api-gateway/src/issuance/issuance.controller.ts
apps/api-gateway/src/issuance/issuance.service.ts
apps/issuance/interfaces/issuance.interfaces.ts
apps/issuance/src/issuance.service.ts

- Added jsonld and indy credential type
- Added W3C credential issuance - create offer by connection Id

feat: add W3C credential issuance by connection id

---

apps/agent-service/src/agent-service.service.ts
apps/api-gateway/src/organization/organization.controller.ts

- stored the did while spinning up the agnet
- fixed the API method issue

fix: set primary did issue

---

apps/api-gateway/src/verification/dto/request-proof.dto.ts

- Change in DTO Example
- Fixes example for DTO

fix: example in DTO

---

taskdef/agent-provisioning-taskdef.json
taskdef/agent-service-taskdef.json
taskdef/api-gateway-taskdef.json
taskdef/connection-taskdef.json
taskdef/ecosystem-taskdef.json
taskdef/issuance-service-taskdef.json
taskdef/ledger-taskdef.json
taskdef/notification-taskdef.json
taskdef/organization-taskdef.json
taskdef/user-taskdef.json
taskdef/utility-taskdef.json
taskdef/verfication-taskdef.json
taskdef/webhook-taskdef.json

Added Taskdef.json files for platform-services

Taskdef.json

---

apps/issuance/interfaces/issuance.interfaces.ts
apps/issuance/src/issuance.processor.ts
apps/issuance/src/issuance.service.ts
libs/common/src/response-messages/index.ts

- Implemented the bulk-issuance retry
- Added logic for last element of the array

feat: bulk issuance retry

---

apps/api-gateway/src/verification/verification.controller.ts
apps/api-gateway/src/verification/verification.service.ts
apps/verification/src/repositories/verification.repository.ts
apps/verification/src/verification.controller.ts
apps/verification/src/verification.module.ts
apps/verification/src/verification.service.ts
libs/common/src/interfaces/verification.interface.ts
libs/common/src/response-messages/index.ts
libs/prisma-service/prisma/migrations/20240607063726_user_org_delete_activity/migration.sql
libs/prisma-service/prisma/migrations/20240607113034_user_org_delete_activity/migration.sql
libs/prisma-service/prisma/schema.prisma
libs/user-activity/repositories/index.ts
libs/user-activity/src/user-activity.service.ts

- Implement delete verification records API
- To delete unnecessary verification records

feat: Delete verification records

---

libs/http-exception.filter.ts

Handle unknown errors in the HTTP exception handler.
The HTTP exception handler does not effectively handle unknown errors, leading to potential issues and vulnerabilities in the application. By implementing a mechanism to handle these unknown errors, we can improve the robustness and reliability of the application.
- Added a try-except block in the HTTP exception handler to catch and handle unknown errors.
- Implemented logging for unknown errors to facilitate debugging and troubleshooting.

fix: handle unknown errors in http exception handler

---

apps/agent-service/src/agent-service.service.ts

- Change in network condition.

fix: network type error fixes

---

apps/api-gateway/src/authz/authz.controller.ts
apps/api-gateway/src/authz/authz.service.ts
apps/user/src/user.controller.ts
apps/user/src/user.service.ts
libs/common/src/interfaces/user.interface.ts

- Change in response while signing up new user
- Return userId while signing up new users

fix: return user details on user signup

---

apps/api-gateway/src/verification/verification.controller.ts
apps/api-gateway/src/verification/verification.service.ts
apps/verification/src/repositories/verification.repository.ts
apps/verification/src/verification.controller.ts
apps/verification/src/verification.service.ts
libs/enum/src/enum.ts
libs/user-activity/repositories/index.ts
libs/user-activity/src/user-activity.service.ts

- Implemented API to delete verification records by orgId
- Implemented store deleted audit trails functionality
- Error handling

feat: delete verification records by orgId

---

apps/api-gateway/src/connection/connection.controller.ts
apps/api-gateway/src/connection/connection.service.ts
apps/api-gateway/src/connection/enums/connections.enum.ts
apps/connection/src/connection.controller.ts
apps/connection/src/connection.module.ts
apps/connection/src/connection.repository.ts
apps/connection/src/connection.service.ts
libs/common/src/interfaces/connection.interface.ts
libs/common/src/response-messages/index.ts
libs/enum/src/enum.ts

- Implemented API to delete connection records by orgId
- Implemented store deleted audit trails functionality
- Error handling
- To enable efficient management and removal of outdated or unnecessary connection data, ensuring data accuracy and system performance

feat: delete connection records

---

libs/prisma-service/prisma/seed.ts

Added validation logic to ensure accurate storage of ledger data.
To prevent incorrect or incomplete data from being stored in the ledger, ensuring data integrity and reliability.
Implemented validation checks during the data storage process to verify the completeness and accuracy of ledger entries before committing them.

fix: added the validation for the store the ledgers data

---

apps/api-gateway/src/issuance/issuance.controller.ts
apps/issuance/src/issuance.service.ts

- Added logger to check file upload flow

fix: test file upload on develop

---

apps/api-gateway/src/organization/dtos/create-organization-dto.ts
apps/organization/repositories/organization.repository.ts
apps/user/interfaces/user.interface.ts
apps/user/repositories/user.repository.ts

- Added geo-location attribute in create-organisation-dto class.
- Select those attributes in create organisation response and in user-profile response.
- Need to store while creating organisation.

fix: create organisation changes and added geo-location attribute in response.

---

apps/issuance/src/issuance.repository.ts
libs/common/src/response-messages/index.ts
libs/prisma-service/prisma/migrations/20240710072128_refactored_file_upload/migration.sql
libs/prisma-service/prisma/schema.prisma

- Refactored file_upload model. Create migration file for new schema update.
- Minor fix in issuance.repository.ts file.

fix: refactored `file_upload` model and minor fix in issuance repository class.

---

apps/api-gateway/src/authz/guards/user-role.guard.ts

What
Added validation logic in the user role guard to ensure that user roles are properly checked before proceeding with the request.
Why
Adding this validation will ensure that only users with the correct roles can access specific routes or perform certain actions.
How
- Introduced validation logic in the user role guard.
- Updated the user role guard to include checks for valid roles.
- Added unit tests to cover the new validation logic.
- Refactored existing tests to accommodate the changes.

fix: add validation in the user role guard

---

apps/api-gateway/src/authz/jwt.strategy.ts

patch:holder role guard

---

apps/ledger/src/schema/repositories/schema.repository.ts
apps/verification/src/repositories/verification.repository.ts
apps/verification/src/verification.service.ts
libs/common/src/interfaces/verification.interface.ts
libs/prisma-service/prisma/migrations/20240731082811_added_schema_id_in_presentations/migration.sql
libs/prisma-service/prisma/migrations/20240731134502_added_email_in_presentations/migration.sql
libs/prisma-service/prisma/schema.prisma

- Stored schemaId in `presentations` table
- Stored encrypted email in `presentations` table
- Modified response of the fetch verification list API as per latest requirements
- Refactored the API for fetching verified proof details by including the retrieval of prettyVC details

refactor: fetch verification list function

---

apps/api-gateway/src/issuance/dtos/issuance.dto.ts

- Added credential formatdata in credential webhook
- To get credential format data in credential webhook

fix: added-credential-data-in-credential-webhook

---

apps/ecosystem/src/ecosystem.service.ts

- Changes in sign endorsement API for dedicated agent.

fix: schema endorsement for dedicated agent

---

apps/verification/src/verification.service.ts
libs/common/src/cast.helper.ts
libs/common/src/common.constant.ts
libs/enum/src/enum.ts

- Refactor create OOB proof request function
- To ensure that attributes are correctly included when creating a proof request

refactor: attributes payload changes while creating a proofrequest

---

apps/ecosystem/src/ecosystem.service.ts

- Resolved fetch schema details issue for endorsement flow

fix: fecth schema details for endorsement flow 

---

apps/ecosystem/src/ecosystem.service.ts
apps/issuance/src/issuance.service.ts
libs/common/src/interfaces/issuance.interface.ts

- Applied validations on issuance date in issuance using connection flow

refactor: applied validations on issuance date 

---

apps/user/src/user.service.ts
libs/client-registration/src/client-registration.service.ts

Encrypt the clientId and client secret to store in DB.
To store secret credential as encrypted in DB
Applied encryption to the clientId and client secret to store in DB.

fix: encrypt clientId and client secret

---

apps/api-gateway/src/connection/dtos/connection.dto.ts
apps/connection/src/connection.repository.ts
apps/connection/src/connection.service.ts
apps/connection/src/interfaces/connection.interfaces.ts

- Implementation of reuse connection using invitation DID

feat: reuse connection using invitation DID

---

apps/api-gateway/src/connection/connection.controller.ts
libs/common/src/common.constant.ts

fix: basic message url

---

libs/prisma-service/prisma/data/credebl-master-table.json

- add the no_ledger type in the ledger table as a master entry
- This is master entry to store the no_ledger master record

fix: add no_ledger type in seed file

---

.env.sample
libs/prisma-service/prisma/data/credebl-master-table.json
libs/prisma-service/prisma/data/geo-location-master-data/countries.csv
libs/prisma-service/prisma/data/geo-location-master-data/states.csv
libs/prisma-service/prisma/scripts/geo_location_data_import.sh
libs/prisma-service/prisma/scripts/update_client_credential_data.sh
libs/prisma-service/prisma/seed.ts

- Added a shell script to store geo-location master records.
- Implemented logic to update client credentials.
- To automate the storage of geo-location data for accurate record-keeping.
- To ensure client credentials are updated efficiently as part of the system's workflow.
- Created a shell script that interacts with the database to insert or update geo-location master records.
- Integrated the script with existing processes to update the clientId and clientSecret in the user table.

refactor: added the shell script for store geo-location master records and update the client credential

---

apps/user/src/user.service.ts

- Fix import issue for certificate share

hotfix:certificate share import

---

apps/api-gateway/src/issuance/issuance.controller.ts
apps/api-gateway/src/issuance/issuance.service.ts
apps/issuance/src/issuance.controller.ts
apps/issuance/src/issuance.repository.ts
apps/issuance/src/issuance.service.ts
libs/common/src/response-messages/index.ts

- Get all file details and file data

feat: get-all-file-details-and-file-data

---

.env.sample

testing DCO
(from ```test-develop-from-main``` to ```test-dco-branch-from-test-develop-from-main```)

chore: test DCO

---

.env.sample

testing 
DCO (from test-develop-from-main to test-qa-from-main)

testPR: test-develop-from-main to test-qa-from-main

---

apps/issuance/src/issuance.service.ts

- Added log for logging job details

chore: added log for logging job details

---

apps/api-gateway/src/issuance/issuance.controller.ts

fix:added log

---

apps/api-gateway/src/authz/socket.gateway.ts
apps/api-gateway/src/issuance/issuance.controller.ts
apps/issuance/src/issuance.service.ts

chore: socket log debug

---

apps/api-gateway/src/authz/socket.gateway.ts
apps/issuance/src/issuance.service.ts

- Added file upload id in socket emitting events

fix: added-file-upload-id-in-socket-emitting events

---

apps/api-gateway/src/authz/socket.gateway.ts
apps/issuance/src/issuance.service.ts

- Added logs for  debugging retry issuance

chore: added logs for  debugging retry issuance 

---

apps/api-gateway/src/authz/socket.gateway.ts
apps/issuance/src/issuance.service.ts

chore:removed debug log

---

apps/api-gateway/src/issuance/issuance.controller.ts

fix: file interceptor

---

apps/api-gateway/src/issuance/issuance.controller.ts

fix: removed logger

---

apps/issuance/src/issuance.service.ts

-  Increased-cache-manager-TTL

fix: increased-cache-manager-TTL

---

apps/issuance/src/issuance.service.ts

fix: changed cache manager ttl

---

.env.sample
apps/issuance/src/issuance.service.ts

- Added env variable for file upload cache ttl
- Made Cache ttl configurable

fix: make-cache-ttl-configurable

---

.env.sample
apps/api-gateway/src/issuance/issuance.controller.ts
apps/issuance/src/issuance.service.ts
libs/common/src/common.constant.ts

- Added field configuration in multer
- Added common constants
- made cache ttl configurable

fix: add-configuration

---

apps/user/src/user.service.ts

- Change google chrome to chromium executable

chore: change google chrome to chromium executables

---

apps/api-gateway/src/organization/dtos/create-organization-dto.ts
apps/api-gateway/src/organization/dtos/update-organization-dto.ts

- Increase organization name and organization description size while creating and updating organization
- Accommodate large org name and large description

fix: increase size for org name and org description

---

apps/issuance/src/issuance.service.ts
libs/common/src/cast.helper.ts

- Applied trim validations on email_identifier field
- Refactored validations for org name

refactor: organization validations

---

libs/common/src/common.constant.ts
libs/common/src/common.utils.ts
libs/prisma-service/prisma/data/credebl-master-table.json

- Added mainnet configuration in `credebl-master-table.json` table
- Added logic for mainnet in `networkNamespace` function

fix: schema creation logic for mainnet

---

apps/api-gateway/src/issuance/dtos/issuance.dto.ts
apps/api-gateway/src/organization/dtos/create-organization-dto.ts
apps/api-gateway/src/organization/dtos/update-organization-dto.ts
apps/issuance/src/issuance.service.ts
libs/common/src/cast.helper.ts
libs/common/src/interfaces/issuance.interface.ts

- Added prettyVc height and width configurations
- Refactored the SQL injection prevention function

refactor: prettyVc configurations

---

apps/api-gateway/src/issuance/dtos/issuance.dto.ts
apps/issuance/interfaces/issuance.interfaces.ts
apps/issuance/src/issuance.service.ts

- Added height and width configurations in prettyVc object for bulk issuance and retry bulk issuance

refactor: added height and width in prettyVc object

---

libs/common/src/common.constant.ts
libs/common/src/common.utils.ts
libs/prisma-service/prisma/data/credebl-master-table.json

- Added mainnet configuration in credebl-master-table.json table
- Added logic for mainnet in networkNamespace function

hotfix:schema creation issue for polygon mainnet

---

.github/workflows/scorecard.yml

- Setup a new workflow for OSSF security tests

Create OSSF scorecard.yml

---

.github/ISSUE_TEMPLATE/DMP_2024.yml
LICENSE
README.md

- Update occurrences of `Blockster Labs` to `Ayanworks`

chore: transition from Blockster Labs to Ayanworks

---

apps/api-gateway/src/authz/authz.controller.ts
apps/api-gateway/src/user/dto/login-user.dto.ts
apps/user/dtos/login-user.dto.ts
apps/user/interfaces/user.interface.ts
apps/user/src/fido/fido.service.ts

- Removed passkey flag from login API DTO
- Added logic for access token after passkey verification

refactor: changed passkey login flow

---

Dockerfiles/Dockerfile.agent-provisioning
Dockerfiles/Dockerfile.agent-service
Dockerfiles/Dockerfile.api-gateway
Dockerfiles/Dockerfile.cloud-wallet
Dockerfiles/Dockerfile.connection
Dockerfiles/Dockerfile.geolocation
Dockerfiles/Dockerfile.issuance
Dockerfiles/Dockerfile.ledger
Dockerfiles/Dockerfile.notification
Dockerfiles/Dockerfile.organization
Dockerfiles/Dockerfile.utility
Dockerfiles/Dockerfile.verification
Dockerfiles/Dockerfile.webhook
apps/agent-provisioning/AFJ/scripts/docker_start_agent.sh

Updated Docker-files to skip puppeteer installation

refactor: updated Dockerfiles

---

apps/organization/src/organization.service.ts
libs/common/src/response-messages/index.ts

fix: ecosystem error handling

---

apps/api-gateway/src/verification/dto/webhook-proof.dto.ts
apps/verification/src/interfaces/verification.interface.ts
apps/verification/src/repositories/verification.repository.ts
libs/prisma-service/prisma/migrations/20241218132640_added_column_in_proof_webhook/migration.sql
libs/prisma-service/prisma/schema.prisma

- Stored decline message for proof webhook

fix: add declined column in proof webhook

---

apps/verification/src/repositories/verification.repository.ts

- Added `errorMessage` parameter in the get app proof

feat: added error message on get all proof

---

Dockerfiles/Dockerfile.api-gateway

- Add OpenSSL installation support for Docker image

Add OpenSSL installation support for Docker image

---

Dockerfiles/Dockerfile.agent-provisioning
Dockerfiles/Dockerfile.agent-service
Dockerfiles/Dockerfile.cloud-wallet
Dockerfiles/Dockerfile.connection
Dockerfiles/Dockerfile.geolocation
Dockerfiles/Dockerfile.issuance
Dockerfiles/Dockerfile.ledger
Dockerfiles/Dockerfile.notification
Dockerfiles/Dockerfile.organization
Dockerfiles/Dockerfile.user
Dockerfiles/Dockerfile.utility
Dockerfiles/Dockerfile.verification
Dockerfiles/Dockerfile.webhook

* Add OpenSSL installation support for Docker image

Fix/add openssl support (#1098)

---

Dockerfiles/Dockerfile.cloud-wallet
package.json

- chore: Platform version upgrade

chore: Platform version upgrade

---

apps/verification/src/verification.service.ts
libs/interceptors/nats.interceptor.ts

- fix: changes in NATS interceptor for error handling

fix: Changes in NATS interceptor for error handling

---

libs/interceptors/nats.interceptor.ts

- revert: Error handling in NATS interceptor.

revert: Error handling in NATS interceptor

---

apps/api-gateway/src/verification/dto/webhook-proof.dto.ts
apps/verification/src/interfaces/verification.interface.ts
apps/verification/src/verification.service.ts

- added parentThreadId in proof flow

fix: added parentThreadId in proof flow

---

apps/api-gateway/src/dtos/create-schema.dto.ts
apps/api-gateway/src/issuance/dtos/issuance.dto.ts
apps/api-gateway/src/issuance/interfaces/index.ts
apps/api-gateway/src/issuance/issuance.controller.ts
apps/api-gateway/src/issuance/issuance.service.ts
apps/issuance/interfaces/issuance.interfaces.ts
apps/issuance/src/issuance.controller.ts
apps/issuance/src/issuance.service.ts
libs/enum/src/enum.ts

- For support array datatype while creating schema

feat: add array data type in schema payload

---

libs/common/src/common.constant.ts

- Changes polygon schema creation endpoint

fix: change schema endpoint

---

apps/agent-service/src/interface/agent-service.interface.ts
apps/api-gateway/src/verification/dto/request-proof.dto.ts
apps/verification/src/interfaces/verification.interface.ts
apps/verification/src/verification.service.ts

- Added `purpose` property in send proof request API

feat: added purpose property in send proof request

---

apps/agent-service/src/interface/agent-service.interface.ts
apps/api-gateway/src/dtos/create-schema.dto.ts
apps/api-gateway/src/issuance/dtos/issuance.dto.ts
apps/api-gateway/src/issuance/interfaces/index.ts
apps/api-gateway/src/issuance/issuance.controller.ts
apps/api-gateway/src/issuance/issuance.service.ts
apps/api-gateway/src/verification/dto/request-proof.dto.ts
apps/api-gateway/src/verification/dto/webhook-proof.dto.ts
apps/api-gateway/src/verification/verification.controller.ts
apps/issuance/interfaces/issuance.interfaces.ts
apps/issuance/src/issuance.controller.ts
apps/issuance/src/issuance.repository.ts
apps/issuance/src/issuance.service.ts
apps/issuance/templates/out-of-band-issuance.template.ts
apps/ledger/src/schema/repositories/schema.repository.ts
apps/ledger/src/schema/schema.controller.ts
apps/ledger/src/schema/schema.interface.ts
apps/ledger/src/schema/schema.service.ts
apps/verification/src/interfaces/verification.interface.ts
apps/verification/src/verification.service.ts
apps/verification/templates/out-of-band-verification.template.ts
libs/common/src/common.constant.ts
libs/enum/src/enum.ts

- Sync changes from DEV to Qa Environment.

Sync changes from DEV to QA (24/02/2025)

---

apps/api-gateway/src/cloud-wallet/cloud-wallet.controller.ts
apps/api-gateway/src/cloud-wallet/dtos/cloudWallet.dto.ts
apps/api-gateway/src/connection/connection.controller.ts
apps/api-gateway/src/fido/fido.controller.ts
apps/api-gateway/src/geo-location/geo-location.controller.ts
apps/api-gateway/src/issuance/issuance.controller.ts
apps/api-gateway/src/notification/notification.controller.ts
apps/api-gateway/src/organization/organization.controller.ts
apps/api-gateway/src/utilities/utilities.controller.ts
apps/api-gateway/src/verification/verification.controller.ts
apps/api-gateway/src/webhook/webhook.controller.ts

modification in API controller summary, description and schema
- cloud-wallet
- geolocation
- notification
- webhooks
- utilities
- credentials
- connections
- organizations
- fido
- verifications

refactor:modification in API summary, description and schema

---

apps/api-gateway/src/verification/dto/request-proof.dto.ts
apps/issuance/src/issuance.service.ts
apps/verification/src/interfaces/verification.interface.ts
apps/verification/src/verification.service.ts
apps/verification/templates/out-of-band-verification.template.ts

- Updated response for oob verification via email

refactor: response for oob verification via email

---

apps/api-gateway/src/agent-service/agent-service.controller.ts
apps/api-gateway/src/authz/authz.controller.ts
apps/api-gateway/src/authz/dtos/forgot-password.dto.ts
apps/api-gateway/src/authz/dtos/reset-password.dto.ts
apps/api-gateway/src/credential-definition/credential-definition.controller.ts
apps/api-gateway/src/dtos/authDto.dto.ts
apps/api-gateway/src/dtos/email-validator.dto.ts
apps/api-gateway/src/dtos/forgot-password.dto.ts
apps/api-gateway/src/dtos/holder-details.dto.ts
apps/api-gateway/src/dtos/holder-reset-password.ts
apps/api-gateway/src/dtos/register-non-admin-user.dto.ts
apps/api-gateway/src/dtos/register-tenant.dto.ts
apps/api-gateway/src/dtos/register-user.dto.ts
apps/api-gateway/src/dtos/reset-password.dto.ts
apps/api-gateway/src/organization/dtos/send-invitation.dto.ts
apps/api-gateway/src/platform/platform.controller.ts
apps/api-gateway/src/schema/schema.controller.ts
apps/api-gateway/src/user/dto/add-user.dto.ts
apps/api-gateway/src/user/dto/create-user.dto.ts
apps/api-gateway/src/user/dto/login-user.dto.ts
apps/api-gateway/src/user/user.controller.ts
apps/organization/repositories/organization.repository.ts
apps/organization/src/organization.service.ts
apps/user/dtos/login-user.dto.ts
apps/user/repositories/user.repository.ts
apps/user/src/user.controller.ts
libs/common/src/response-messages/index.ts

- Done changes for payload example and API description.
- Done changes for swagger API documentation.

refactor: swagger documentation changes for auth, schema, ledger, credential-definition, agent and user controllers.

---

apps/organization/repositories/organization.repository.ts

- Added orgDid in get all orgs API response

chore: added orgdid in get all orgs response

---

apps/verification/src/verification.service.ts

- Added `threadId` and `outOfBandRecordId` in create OOB proof request via email API response.

chore: updated response for oob email verification

---

Dockerfiles/Dockerfile.verification

- Added Openssl installation in Dockerfiles

chore: updated Dockerfile for openssl installation

---

apps/api-gateway/src/agent-service/agent-service.controller.ts
apps/api-gateway/src/fido/fido.controller.ts
apps/api-gateway/src/organization/organization.controller.ts

- Fix: added API params validation for orgId in agent health API.

fix: added API params validations

---

apps/issuance/src/issuance.repository.ts
apps/issuance/src/issuance.service.ts
apps/ledger/src/schema/repositories/schema.repository.ts
apps/ledger/src/schema/schema.controller.ts
apps/ledger/src/schema/schema.service.ts

- Done changes for](refactor: Added conditions to get issued credential list for OOB email issuance.
(https://credebl.atlassian.net/browse/CREDEBL-551)

refactor: Added conditions to get issued credential list for OOB email issuance.

---

compass.yml

fix: added compass.yml file

---

apps/api-gateway/src/dtos/create-schema.dto.ts
apps/api-gateway/src/schema/dtos/update-schema-dto.ts
apps/api-gateway/src/schema/schema.controller.ts
apps/api-gateway/src/schema/schema.service.ts
apps/ledger/src/schema/interfaces/schema-payload.interface.ts
apps/ledger/src/schema/interfaces/schema.interface.ts
apps/ledger/src/schema/repositories/schema.repository.ts
apps/ledger/src/schema/schema.controller.ts
apps/ledger/src/schema/schema.service.ts
compass.yml
libs/common/src/response-messages/index.ts
libs/prisma-service/prisma/migrations/20250305061413_add_column_alias_in_schema_table/migration.sql
libs/prisma-service/prisma/schema.prisma

- Added alias for schema
- Updated schema alias (API excluded from Swagger)
- Included alias in "Get All Schema" response
- Added schema alias in "Get Schema by Schema ID" API
- Added compass.yaml file

Sync latest changes from develop into qa.

---

apps/organization/repositories/organization.repository.ts

- Add tenant id in get org info API
- To get tenantId in the Get Org Info API response

fix:add tenant id in get org info

---

apps/api-gateway/src/dtos/geo-location-dto.ts
apps/api-gateway/src/organization/dtos/create-organization-dto.ts
apps/api-gateway/src/organization/dtos/update-organization-dto.ts
apps/organization/interfaces/organization.interface.ts
apps/organization/repositories/organization.repository.ts

- Refactored update organization API to support updation of country, state and city fields.

refactor: update organization API to support updation of country, state and city

---

apps/api-gateway/src/verification/verification.controller.ts
apps/api-gateway/src/verification/verification.service.ts
apps/verification/src/repositories/verification.repository.ts
apps/verification/src/verification.controller.ts
apps/verification/src/verification.service.ts

- Implemented `get verified presentations count by issuer Id` API.

feat: Get verified presentations count by issuer Id

---

.env.demo

chore: update .env.demo file

---

apps/issuance/src/issuance.repository.ts
apps/issuance/src/issuance.service.ts

- Added validations to verify the provided organization and template ledgerId during credential issuance via connection, email, and out-of-band (OOB) methods.

feat: Validations for organization and template ledgerId in all issuance methods

---

apps/issuance/src/issuance.repository.ts
apps/issuance/src/issuance.service.ts

- Sync up changes from DEV to QA

merge: sync up changes from DEV to QA.

---

.github/workflows/continuous-delivery.yml
Dockerfiles/Dockerfile.seed

- Added Dockerfile for seed.
- Added seed and organization in gitactions

feat: added seed dockerfile

---

Dockerfiles/Dockerfile.cloud-wallet
Dockerfiles/Dockerfile.seed
Dockerfiles/Dockerfile.user
Dockerfiles/Dockerfile.utility
libs/prisma-service/prisma/scripts/geo_location_data_import.sh
libs/prisma-service/prisma/scripts/update_client_credential_data.sh

- Updated Dockerfiles to use node:18-alpine for a lighter runtime environment.
- Modified Prisma shell scripts to use sh syntax for compatibility with the Alpine-based seed Docker image.

refactor: update dockerfile to reduce dockerimages

---

.github/ISSUE_TEMPLATE/FEATURE-REQUEST.yml
.github/ISSUE_TEMPLATE/bug_report.yml

update template content

---

apps/organization/repositories/organization.repository.ts

- Updated function for fetching organization details by id.

update: modify get organization query

---

apps/agent-service/src/agent-service.controller.ts
apps/agent-service/src/agent-service.service.ts
apps/api-gateway/src/agent-service/agent-service.controller.ts
apps/api-gateway/src/agent-service/agent-service.service.ts
apps/api-gateway/src/agent-service/dto/agent-service.dto.ts
apps/api-gateway/src/main.ts
libs/common/src/common.constant.ts
libs/common/src/custom-overrideable-validation-pipe.ts
libs/enum/src/enum.ts

feat: add sign and verify api

---

apps/api-gateway/src/agent-service/agent-service.controller.ts
apps/api-gateway/src/agent-service/dto/agent-service.dto.ts
libs/common/src/response-messages/index.ts

fix: success message and othe minor changes

fix: success message and othe minor changes

---

apps/issuance/src/issuance.repository.ts
libs/common/src/response-messages/index.ts
libs/prisma-service/prisma/migrations/20250724161232_added_connection_for_credentials_with_connection_table/migration.sql
libs/prisma-service/prisma/schema.prisma

Added prisma relation for credentials and connections table
updated the api to get all credentials to fetch their label field

Added prisma relation for credentials and connections table

---

apps/agent-service/src/agent-service.service.ts
apps/connection/src/connection.service.ts
apps/verification/src/verification.service.ts
libs/common/src/common.constant.ts
libs/common/src/common.service.ts
libs/common/src/common.utils.ts
libs/common/src/response-messages/index.ts

####What
- Changed agent URL endpoint
- Changed agent token for `createSecp256k1KeyPair` method

refactor: changes agent endpoint

---

.github/dco.yml

fix: DCO remediation ability

---

apps/ledger/src/schema/schema.service.ts

- Fixed all schema crash when no organization

Fix crash on all schema view when no organization exists

---

apps/issuance/src/issuance.repository.ts
apps/issuance/src/issuance.service.ts
libs/common/src/common.constant.ts

- Added fix for connection , email and bulk issuance to save schema id during issuance

fix: Save schemaId during connection, email, and bulk issuance

---

apps/user/src/user.service.ts

- fix: Fetch session logic for passkey flow

fix: session logic for passkey flow

---

apps/issuance/enum/issuance.enum.ts
apps/issuance/src/issuance.repository.ts
apps/verification/src/interfaces/verification.interface.ts
apps/verification/src/repositories/verification.repository.ts

- Updated search parameter for Credentials and Verification api

feat: Updated search parameter for Credentials and Verification api

---

apps/issuance/src/issuance.repository.ts

- remediation fix for dev to qa

fix: DCO issue fix through remediation

---

apps/issuance/src/issuance.repository.ts

- fix DCO issue for develop to qa

fix: Dco through remediation for develop branch

---

apps/agent-service/src/agent-service.service.ts
libs/common/src/common.constant.ts

- Badge issuance error for non wallet flow for issuance

fix: Badge issuance error for non wallet flow for issuance

---

apps/api-gateway/src/user/user.controller.ts
apps/api-gateway/src/user/user.service.ts
apps/organization/src/organization.service.ts
apps/user/interfaces/user.interface.ts
apps/user/repositories/user.repository.ts
apps/user/src/user.controller.ts
apps/user/src/user.service.ts
libs/prisma-service/prisma/migrations/20250829091021_add_expiresat_in_session_table/migration.sql
libs/prisma-service/prisma/schema.prisma

Once user logged in delete the inactive/expired session from database

Inactive session deletion

---

apps/api-gateway/src/agent-service/agent-service.controller.ts

- Badge verification page issue

fix: Badge verification page issue

---

Dockerfiles/Dockerfile.agent-provisioning
apps/agent-provisioning/AFJ/scripts/fargate.sh
apps/agent-provisioning/AFJ/scripts/start_agent_ecs.sh
apps/agent-provisioning/src/agent-provisioning.service.ts

* fix:credo-controller service spin up ECS ec2
* update fargate.sh-credo spin up script
* fix: fargate.sh inbound port to number from string

feat/credo-spinup-script (#1427)

---

apps/api-gateway/src/oid4vc-issuance/dtos/oid4vc-issuer-template.dto.ts
apps/api-gateway/src/oid4vc-issuance/oid4vc-issuance.controller.ts
apps/api-gateway/src/oid4vc-issuance/oid4vc-issuance.service.ts
apps/oid4vc-issuance/libs/helpers/credential-sessions.builder.ts
apps/oid4vc-issuance/libs/helpers/issuer.metadata.ts
apps/oid4vc-issuance/src/oid4vc-issuance.controller.ts
apps/oid4vc-issuance/src/oid4vc-issuance.service.ts

- change issuerId to ID
- update delete issuer logic
- updated builder method (Template and offer creation)

refactor: update oid4vc flows
